// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `topgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rom_ctrl__rom", '{
        '{32'h00000000, 32'h00007fff}
    }},
    '{"rom_ctrl__regs", '{
        '{32'h40007000, 32'h4000707f}
    }},
    '{"sram_ctrl__regs", '{
        '{32'h40008000, 32'h4000803f}
    }},
    '{"sram_ctrl__ram", '{
        '{32'h10000000, 32'h1001ffff}
    }},
    '{"flash_ctrl__core", '{
        '{32'h40009000, 32'h400091ff}
    }},
    '{"flash_ctrl__prim", '{
        '{32'h4000a000, 32'h4000a07f}
    }},
    '{"flash_ctrl__mem", '{
        '{32'h20000000, 32'h2003ffff}
    }},
    '{"aes", '{
        '{32'h40000000, 32'h400000ff}
    }},
    '{"hmac", '{
        '{32'h40010000, 32'h40011fff}
    }},
    '{"kmac", '{
        '{32'h40020000, 32'h40020fff}
    }},
    '{"csrng", '{
        '{32'h40030000, 32'h4003007f}
    }},
    '{"entropy_src", '{
        '{32'h40040000, 32'h400400ff}
    }},
    '{"edn0", '{
        '{32'h40005000, 32'h4000507f}
    }},
    '{"otbn", '{
        '{32'h40080000, 32'h4008ffff}
    }},
    '{"keymgr", '{
        '{32'h40100000, 32'h401000ff}
    }},
    '{"lc_ctrl__regs", '{
        '{32'h40101000, 32'h401010ff}
    }},
    '{"alert_handler", '{
        '{32'h40120000, 32'h401207ff}
    }},
    '{"otp_ctrl__core", '{
        '{32'h40130000, 32'h40130fff}
    }},
    '{"otp_macro__prim", '{
        '{32'h40138000, 32'h4013801f}
    }},
    '{"sensor_ctrl", '{
        '{32'h40140000, 32'h4014007f}
    }},
    '{"spi_device", '{
        '{32'h40200000, 32'h40201fff}
    }},
    '{"gpio", '{
        '{32'h40210000, 32'h4021007f}
    }},
    '{"i2c0", '{
        '{32'h40220000, 32'h4022007f}
    }},
    '{"uart0", '{
        '{32'h40230000, 32'h4023003f}
    }},
    '{"rv_plic", '{
        '{32'h48000000, 32'h4fffffff}
    }},
    '{"rv_timer", '{
        '{32'h40310000, 32'h403101ff}
    }},
    '{"aon_timer_aon", '{
        '{32'h40320000, 32'h4032003f}
    }},
    '{"pwrmgr_aon", '{
        '{32'h40330000, 32'h4033007f}
    }},
    '{"clkmgr_aon", '{
        '{32'h40340000, 32'h4034003f}
    }},
    '{"rstmgr_aon", '{
        '{32'h40350000, 32'h4035003f}
    }},
    '{"pinmux_aon", '{
        '{32'h40360000, 32'h403603ff}
    }},
    '{"rv_core_ibex__cfg", '{
        '{32'h4000b000, 32'h4000b0ff}
    }}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "rom_ctrl__rom",
        "sram_ctrl__ram",
        "flash_ctrl__mem"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "sram_ctrl__ram",
        "sram_ctrl__regs",
        "flash_ctrl__core",
        "flash_ctrl__prim",
        "flash_ctrl__mem",
        "aes",
        "hmac",
        "kmac",
        "csrng",
        "entropy_src",
        "edn0",
        "otbn",
        "keymgr",
        "lc_ctrl__regs",
        "alert_handler",
        "otp_ctrl__core",
        "otp_macro__prim",
        "sensor_ctrl",
        "spi_device",
        "gpio",
        "i2c0",
        "uart0",
        "rv_plic",
        "rv_timer",
        "aon_timer_aon",
        "pwrmgr_aon",
        "clkmgr_aon",
        "rstmgr_aon",
        "pinmux_aon",
        "rv_core_ibex__cfg"}}
};
