// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_main package generated by `tlgen.py` tool

package tl_main_pkg;

  localparam logic [31:0] ADDR_SPACE_ROM_CTRL__ROM     = 32'h 00000000;
  localparam logic [31:0] ADDR_SPACE_ROM_CTRL__REGS    = 32'h 40007000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL__REGS   = 32'h 40008000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL__RAM    = 32'h 10000000;
  localparam logic [31:0] ADDR_SPACE_FLASH_CTRL__CORE  = 32'h 40009000;
  localparam logic [31:0] ADDR_SPACE_FLASH_CTRL__PRIM  = 32'h 4000a000;
  localparam logic [31:0] ADDR_SPACE_FLASH_CTRL__MEM   = 32'h 20000000;
  localparam logic [31:0] ADDR_SPACE_AES               = 32'h 40000000;
  localparam logic [31:0] ADDR_SPACE_HMAC              = 32'h 40010000;
  localparam logic [31:0] ADDR_SPACE_KMAC              = 32'h 40020000;
  localparam logic [31:0] ADDR_SPACE_CSRNG             = 32'h 40030000;
  localparam logic [31:0] ADDR_SPACE_ENTROPY_SRC       = 32'h 40040000;
  localparam logic [31:0] ADDR_SPACE_EDN0              = 32'h 40005000;
  localparam logic [31:0] ADDR_SPACE_OTBN              = 32'h 40080000;
  localparam logic [31:0] ADDR_SPACE_KEYMGR            = 32'h 40100000;
  localparam logic [31:0] ADDR_SPACE_LC_CTRL__REGS     = 32'h 40101000;
  localparam logic [31:0] ADDR_SPACE_ALERT_HANDLER     = 32'h 40120000;
  localparam logic [31:0] ADDR_SPACE_OTP_CTRL__CORE    = 32'h 40130000;
  localparam logic [31:0] ADDR_SPACE_OTP_MACRO__PRIM   = 32'h 40138000;
  localparam logic [31:0] ADDR_SPACE_SENSOR_CTRL       = 32'h 40140000;
  localparam logic [31:0] ADDR_SPACE_SPI_DEVICE        = 32'h 40200000;
  localparam logic [31:0] ADDR_SPACE_GPIO              = 32'h 40210000;
  localparam logic [31:0] ADDR_SPACE_I2C0              = 32'h 40220000;
  localparam logic [31:0] ADDR_SPACE_UART0             = 32'h 40230000;
  localparam logic [31:0] ADDR_SPACE_RV_PLIC           = 32'h 48000000;
  localparam logic [31:0] ADDR_SPACE_RV_TIMER          = 32'h 40310000;
  localparam logic [31:0] ADDR_SPACE_AON_TIMER_AON     = 32'h 40320000;
  localparam logic [31:0] ADDR_SPACE_PWRMGR_AON        = 32'h 40330000;
  localparam logic [31:0] ADDR_SPACE_CLKMGR_AON        = 32'h 40340000;
  localparam logic [31:0] ADDR_SPACE_RSTMGR_AON        = 32'h 40350000;
  localparam logic [31:0] ADDR_SPACE_PINMUX_AON        = 32'h 40360000;
  localparam logic [31:0] ADDR_SPACE_RV_CORE_IBEX__CFG = 32'h 4000b000;

  localparam logic [31:0] ADDR_MASK_ROM_CTRL__ROM     = 32'h 00007fff;
  localparam logic [31:0] ADDR_MASK_ROM_CTRL__REGS    = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL__REGS   = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL__RAM    = 32'h 0001ffff;
  localparam logic [31:0] ADDR_MASK_FLASH_CTRL__CORE  = 32'h 000001ff;
  localparam logic [31:0] ADDR_MASK_FLASH_CTRL__PRIM  = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_FLASH_CTRL__MEM   = 32'h 0003ffff;
  localparam logic [31:0] ADDR_MASK_AES               = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_HMAC              = 32'h 00001fff;
  localparam logic [31:0] ADDR_MASK_KMAC              = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_CSRNG             = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_ENTROPY_SRC       = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_EDN0              = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_OTBN              = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_KEYMGR            = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_LC_CTRL__REGS     = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_ALERT_HANDLER     = 32'h 000007ff;
  localparam logic [31:0] ADDR_MASK_OTP_CTRL__CORE    = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_OTP_MACRO__PRIM   = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_SENSOR_CTRL       = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_SPI_DEVICE        = 32'h 00001fff;
  localparam logic [31:0] ADDR_MASK_GPIO              = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_I2C0              = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_UART0             = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_RV_PLIC           = 32'h 07ffffff;
  localparam logic [31:0] ADDR_MASK_RV_TIMER          = 32'h 000001ff;
  localparam logic [31:0] ADDR_MASK_AON_TIMER_AON     = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_PWRMGR_AON        = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_CLKMGR_AON        = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_RSTMGR_AON        = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_PINMUX_AON        = 32'h 000003ff;
  localparam logic [31:0] ADDR_MASK_RV_CORE_IBEX__CFG = 32'h 000000ff;

  localparam int N_HOST   = 2;
  localparam int N_DEVICE = 32;

  typedef enum int {
    TlRomCtrlRom = 0,
    TlRomCtrlRegs = 1,
    TlSramCtrlRegs = 2,
    TlSramCtrlRam = 3,
    TlFlashCtrlCore = 4,
    TlFlashCtrlPrim = 5,
    TlFlashCtrlMem = 6,
    TlAes = 7,
    TlHmac = 8,
    TlKmac = 9,
    TlCsrng = 10,
    TlEntropySrc = 11,
    TlEdn0 = 12,
    TlOtbn = 13,
    TlKeymgr = 14,
    TlLcCtrlRegs = 15,
    TlAlertHandler = 16,
    TlOtpCtrlCore = 17,
    TlOtpMacroPrim = 18,
    TlSensorCtrl = 19,
    TlSpiDevice = 20,
    TlGpio = 21,
    TlI2C0 = 22,
    TlUart0 = 23,
    TlRvPlic = 24,
    TlRvTimer = 25,
    TlAonTimerAon = 26,
    TlPwrmgrAon = 27,
    TlClkmgrAon = 28,
    TlRstmgrAon = 29,
    TlPinmuxAon = 30,
    TlRvCoreIbexCfg = 31
  } tl_device_e;

  typedef enum int {
    TlRvCoreIbexCorei = 0,
    TlRvCoreIbexCored = 1
  } tl_host_e;

endpackage
