// Copyright 2026 SafeRoot Project
// SPDX-License-Identifier: Apache-2.0
//
// aes_drv.c — AES-256 hardware accelerator driver for SafeRoot
// Register offsets from aes_reg_pkg.sv (auto-generated by reggen)
//
// Protocol: write key -> write IV (if needed) -> configure CTRL ->
//           write DATA_IN -> poll STATUS.OUTPUT_VALID -> read DATA_OUT

#include "aes_drv.h"

// ---------------------------------------------------------------------------
// AES register offsets (from aes_reg_pkg.sv)
// ---------------------------------------------------------------------------
#define AES_ALERT_TEST        0x00
#define AES_KEY_SHARE0_0      0x04  // KEY_SHARE0[0..7] at 0x04..0x20
#define AES_KEY_SHARE1_0      0x24  // KEY_SHARE1[0..7] at 0x24..0x40
#define AES_IV_0              0x44  // IV[0..3] at 0x44..0x50
#define AES_DATA_IN_0         0x54  // DATA_IN[0..3] at 0x54..0x60
#define AES_DATA_OUT_0        0x64  // DATA_OUT[0..3] at 0x64..0x70
#define AES_CTRL_SHADOWED     0x74  // Control register (shadowed)
#define AES_CTRL_AUX_SHADOWED 0x78  // Auxiliary control
#define AES_CTRL_AUX_REGWEN   0x7C  // Aux control lock
#define AES_TRIGGER           0x80  // Trigger register
#define AES_STATUS            0x84  // Status register (RO)

// ---------------------------------------------------------------------------
// CTRL_SHADOWED bit fields
// ---------------------------------------------------------------------------
// [1:0]   OPERATION: 01=encrypt, 10=decrypt
// [7:2]   MODE: 6-bit one-hot (ECB=1, CBC=2, CFB=4, OFB=8, CTR=16)
// [10:8]  KEY_LEN: 001=128, 010=192, 100=256
// [11]    SIDELOAD
// [14:12] PRNG_RESEED_RATE
// [15]    MANUAL_OPERATION
#define AES_CTRL_OP_SHIFT       0
#define AES_CTRL_MODE_SHIFT     2
#define AES_CTRL_KEYLEN_SHIFT   8
#define AES_CTRL_KEYLEN_256     (0x4 << AES_CTRL_KEYLEN_SHIFT)

// ---------------------------------------------------------------------------
// TRIGGER register bits
// ---------------------------------------------------------------------------
#define AES_TRIGGER_START              BIT(0)
#define AES_TRIGGER_KEY_IV_DATA_CLEAR  BIT(1)
#define AES_TRIGGER_DATA_OUT_CLEAR     BIT(2)
#define AES_TRIGGER_PRNG_RESEED        BIT(3)

// ---------------------------------------------------------------------------
// STATUS register bits
// ---------------------------------------------------------------------------
#define AES_STATUS_IDLE          BIT(0)
#define AES_STATUS_STALL         BIT(1)
#define AES_STATUS_OUTPUT_LOST   BIT(2)
#define AES_STATUS_OUTPUT_VALID  BIT(3)
#define AES_STATUS_INPUT_READY   BIT(4)

#define AES_BASE SAFEROOT_AES_BASE

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

// Wait for AES to become idle, with timeout.
static hal_status_t aes_wait_idle(void) {
    for (uint32_t i = 0; i < HAL_TIMEOUT_CYCLES; i++) {
        if (REG32_READ(AES_BASE + AES_STATUS) & AES_STATUS_IDLE) {
            return kHalOk;
        }
    }
    return kHalTimeout;
}

// Write to shadowed register (needs two identical writes)
static void aes_write_shadowed(uint32_t offset, uint32_t val) {
    REG32_WRITE(AES_BASE + offset, val);
    REG32_WRITE(AES_BASE + offset, val);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

bool aes_is_idle(void) {
    return (REG32_READ(AES_BASE + AES_STATUS) & AES_STATUS_IDLE) != 0;
}

hal_status_t aes_init(aes_op_t op, aes_mode_t mode,
                      const uint32_t key[8], const uint32_t *iv) {
    if (key == (void *)0) return kHalBadArg;

    // Wait for idle
    hal_status_t st = aes_wait_idle();
    if (st != kHalOk) return st;

    // Write key to KEY_SHARE0 (actual key), KEY_SHARE1 = 0 (no masking)
    for (int i = 0; i < 8; i++) {
        REG32_WRITE(AES_BASE + AES_KEY_SHARE0_0 + (uint32_t)(i * 4), key[i]);
        REG32_WRITE(AES_BASE + AES_KEY_SHARE1_0 + (uint32_t)(i * 4), 0);
    }

    // Write IV if provided (required for CBC, CFB, OFB, CTR)
    if (iv != (void *)0) {
        for (int i = 0; i < 4; i++) {
            REG32_WRITE(AES_BASE + AES_IV_0 + (uint32_t)(i * 4), iv[i]);
        }
    }

    // Configure: AES-256, automatic mode, selected operation and mode
    uint32_t ctrl = ((uint32_t)op << AES_CTRL_OP_SHIFT) |
                    ((uint32_t)mode << AES_CTRL_MODE_SHIFT) |
                    AES_CTRL_KEYLEN_256;
    aes_write_shadowed(AES_CTRL_SHADOWED, ctrl);

    return kHalOk;
}

hal_status_t aes_process_block(const uint32_t data_in[4],
                               uint32_t data_out[4]) {
    // Wait for INPUT_READY
    for (uint32_t i = 0; i < HAL_TIMEOUT_CYCLES; i++) {
        if (REG32_READ(AES_BASE + AES_STATUS) & AES_STATUS_INPUT_READY) {
            goto input_ready;
        }
    }
    return kHalTimeout;

input_ready:
    // Write all 4 input data registers (triggers encryption in auto mode)
    for (int i = 0; i < 4; i++) {
        REG32_WRITE(AES_BASE + AES_DATA_IN_0 + (uint32_t)(i * 4), data_in[i]);
    }

    // Poll for OUTPUT_VALID
    for (uint32_t i = 0; i < HAL_TIMEOUT_CYCLES; i++) {
        if (REG32_READ(AES_BASE + AES_STATUS) & AES_STATUS_OUTPUT_VALID) {
            goto output_valid;
        }
    }
    return kHalTimeout;

output_valid:
    // Read all 4 output data registers
    for (int i = 0; i < 4; i++) {
        data_out[i] = REG32_READ(AES_BASE + AES_DATA_OUT_0 + (uint32_t)(i * 4));
    }

    return kHalOk;
}

void aes_clear(void) {
    // Trigger clearing of key, IV, data_in, data_out and PRNG reseed
    REG32_WRITE(AES_BASE + AES_TRIGGER,
                AES_TRIGGER_KEY_IV_DATA_CLEAR |
                AES_TRIGGER_DATA_OUT_CLEAR |
                AES_TRIGGER_PRNG_RESEED);
}
