// Copyright 2026 SafeRoot Project
// SPDX-License-Identifier: Apache-2.0
//
// hmac_drv.c — HMAC-SHA256 hardware accelerator driver for SafeRoot
// Register offsets from hmac_reg_pkg.sv (auto-generated by reggen)
//
// Protocol: configure CFG -> write KEY (if HMAC) -> CMD.hash_start ->
//           write data to MSG_FIFO -> CMD.hash_process -> poll hmac_done ->
//           read DIGEST

#include "hmac_drv.h"

// ---------------------------------------------------------------------------
// HMAC register offsets (from hmac_reg_pkg.sv)
// ---------------------------------------------------------------------------
#define HMAC_INTR_STATE       0x00
#define HMAC_INTR_ENABLE      0x04
#define HMAC_INTR_TEST        0x08
#define HMAC_ALERT_TEST       0x0C
#define HMAC_CFG              0x10  // Configuration register
#define HMAC_CMD              0x14  // Command register (W1C)
#define HMAC_STATUS           0x18  // Status register (RO)
#define HMAC_ERR_CODE         0x1C  // Error code (RO)
#define HMAC_WIPE_SECRET      0x20  // Write to wipe internal state
#define HMAC_KEY_0            0x24  // KEY[0..7] at 0x24..0x40
// KEY[8..31] at 0x44..0xA0 (for larger keys, we only use 0..7 for 256-bit)
#define HMAC_DIGEST_0         0xA4  // DIGEST[0..7] at 0xA4..0xC0
// DIGEST[8..15] at 0xC4..0xE0 (for SHA-384/512)
#define HMAC_MSG_LENGTH_LOWER 0xE4
#define HMAC_MSG_LENGTH_UPPER 0xE8
#define HMAC_MSG_FIFO         0x1000  // 4 KB window for message data

// ---------------------------------------------------------------------------
// CFG register bit definitions
// ---------------------------------------------------------------------------
// [0]    hmac_en    — 1 = HMAC mode, 0 = SHA-only
// [1]    sha_en     — 1 = enable SHA engine
// [2]    endian_swap — 1 = big-endian input
// [3]    digest_swap — 1 = big-endian digest output
// [4]    key_swap   — 1 = swap key endianness
// [8:5]  digest_size — one-hot: 1=SHA256, 2=SHA384, 4=SHA512
// [14:9] key_length — one-hot: 1=128, 2=256, 4=384, 8=512, 16=1024
#define HMAC_CFG_HMAC_EN       BIT(0)
#define HMAC_CFG_SHA_EN        BIT(1)
#define HMAC_CFG_ENDIAN_SWAP   BIT(2)
#define HMAC_CFG_DIGEST_SWAP   BIT(3)
#define HMAC_CFG_DIGEST_SHA256 (0x01 << 5)  // digest_size = SHA2_256
#define HMAC_CFG_KEYLEN_256    (0x02 << 9)  // key_length = Key_256

// ---------------------------------------------------------------------------
// CMD register bit definitions (W1C — write 1 to trigger)
// ---------------------------------------------------------------------------
#define HMAC_CMD_HASH_START    BIT(0)
#define HMAC_CMD_HASH_PROCESS  BIT(1)
#define HMAC_CMD_HASH_STOP     BIT(2)
#define HMAC_CMD_HASH_CONTINUE BIT(3)

// ---------------------------------------------------------------------------
// STATUS register bit definitions
// ---------------------------------------------------------------------------
#define HMAC_STATUS_IDLE       BIT(0)
#define HMAC_STATUS_FIFO_EMPTY BIT(1)
#define HMAC_STATUS_FIFO_FULL  BIT(2)

// ---------------------------------------------------------------------------
// INTR_STATE bit for hmac_done
// ---------------------------------------------------------------------------
#define HMAC_INTR_HMAC_DONE    BIT(0)
#define HMAC_INTR_FIFO_EMPTY   BIT(1)
#define HMAC_INTR_HMAC_ERR     BIT(2)

#define HMAC_BASE SAFEROOT_HMAC_BASE

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

static hal_status_t hmac_wait_idle(void) {
    for (uint32_t i = 0; i < HAL_TIMEOUT_CYCLES; i++) {
        if (REG32_READ(HMAC_BASE + HMAC_STATUS) & HMAC_STATUS_IDLE) {
            return kHalOk;
        }
    }
    return kHalTimeout;
}

static hal_status_t hmac_wait_done(void) {
    for (uint32_t i = 0; i < HAL_TIMEOUT_CYCLES; i++) {
        if (REG32_READ(HMAC_BASE + HMAC_INTR_STATE) & HMAC_INTR_HMAC_DONE) {
            // Clear the interrupt by writing 1
            REG32_WRITE(HMAC_BASE + HMAC_INTR_STATE, HMAC_INTR_HMAC_DONE);
            return kHalOk;
        }
    }
    return kHalTimeout;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

hal_status_t hmac_init(const uint32_t *key) {
    hal_status_t st = hmac_wait_idle();
    if (st != kHalOk) return st;

    // Disable SHA engine first to reset state
    REG32_WRITE(HMAC_BASE + HMAC_CFG, 0);

    // Clear pending interrupts
    REG32_WRITE(HMAC_BASE + HMAC_INTR_STATE, 0xFFFFFFFF);
    // Disable all interrupts (polling mode)
    REG32_WRITE(HMAC_BASE + HMAC_INTR_ENABLE, 0);

    // Configure: SHA-256, big-endian input (standard), big-endian digest
    uint32_t cfg = HMAC_CFG_SHA_EN | HMAC_CFG_ENDIAN_SWAP |
                   HMAC_CFG_DIGEST_SWAP | HMAC_CFG_DIGEST_SHA256;

    if (key != (void *)0) {
        cfg |= HMAC_CFG_HMAC_EN | HMAC_CFG_KEYLEN_256;
        // Write 256-bit key (8 words) — must write while idle, before sha_en
        // Temporarily set cfg without sha_en to allow key write
        REG32_WRITE(HMAC_BASE + HMAC_CFG, cfg & ~HMAC_CFG_SHA_EN);
        for (int i = 0; i < 8; i++) {
            REG32_WRITE(HMAC_BASE + HMAC_KEY_0 + (uint32_t)(i * 4), key[i]);
        }
        // Zero out unused key registers (KEY[8..31])
        for (int i = 8; i < 32; i++) {
            REG32_WRITE(HMAC_BASE + HMAC_KEY_0 + (uint32_t)(i * 4), 0);
        }
    }

    // Enable SHA engine
    REG32_WRITE(HMAC_BASE + HMAC_CFG, cfg);

    // Issue hash_start command
    REG32_WRITE(HMAC_BASE + HMAC_CMD, HMAC_CMD_HASH_START);

    return kHalOk;
}

hal_status_t hmac_update(const void *data, uint32_t len) {
    const uint32_t *words = (const uint32_t *)data;
    uint32_t word_count = len / 4;

    for (uint32_t i = 0; i < word_count; i++) {
        // Wait for FIFO to have space
        while (REG32_READ(HMAC_BASE + HMAC_STATUS) & HMAC_STATUS_FIFO_FULL) {
            // spin — FIFO full causes back-pressure
        }
        REG32_WRITE(HMAC_BASE + HMAC_MSG_FIFO, words[i]);
    }

    return kHalOk;
}

hal_status_t hmac_final(uint32_t digest[8]) {
    // Signal end of message
    REG32_WRITE(HMAC_BASE + HMAC_CMD, HMAC_CMD_HASH_PROCESS);

    // Wait for completion
    hal_status_t st = hmac_wait_done();
    if (st != kHalOk) return st;

    // Read 256-bit digest (8 words)
    for (int i = 0; i < 8; i++) {
        digest[i] = REG32_READ(HMAC_BASE + HMAC_DIGEST_0 + (uint32_t)(i * 4));
    }

    return kHalOk;
}

hal_status_t sha256(const void *data, uint32_t len, uint32_t digest[8]) {
    hal_status_t st;
    st = hmac_init((void *)0);  // SHA-only mode (no key)
    if (st != kHalOk) return st;
    st = hmac_update(data, len);
    if (st != kHalOk) return st;
    return hmac_final(digest);
}

void hmac_wipe(uint32_t wipe_val) {
    REG32_WRITE(HMAC_BASE + HMAC_WIPE_SECRET, wipe_val);
}
