// Copyright 2026 SafeRoot Project
// SPDX-License-Identifier: Apache-2.0
//
// uart_drv.c — UART driver for SafeRoot (OpenTitan UART IP)
// Register offsets from uart_reg_pkg.sv (auto-generated by reggen)

#include "uart_drv.h"

// ---------------------------------------------------------------------------
// UART register offsets (from uart_reg_pkg.sv)
// ---------------------------------------------------------------------------
#define UART_INTR_STATE     0x00  // Interrupt State
#define UART_INTR_ENABLE    0x04  // Interrupt Enable
#define UART_INTR_TEST      0x08  // Interrupt Test
#define UART_ALERT_TEST     0x0C  // Alert Test
#define UART_CTRL           0x10  // Control register
#define UART_STATUS         0x14  // Status register (RO)
#define UART_RDATA          0x18  // RX data (RO, 8-bit)
#define UART_WDATA          0x1C  // TX data (WO, 8-bit)
#define UART_FIFO_CTRL      0x20  // FIFO control
#define UART_FIFO_STATUS    0x24  // FIFO status (RO)
#define UART_OVRD           0x28  // TX pin override
#define UART_VAL            0x2C  // Oversampled RX values
#define UART_TIMEOUT_CTRL   0x30  // RX timeout control

// ---------------------------------------------------------------------------
// CTRL register bit definitions
// ---------------------------------------------------------------------------
// [0]     TX enable
// [1]     RX enable
// [2]     NF — noise filter enable
// [4]     SLPBK — system loopback
// [5]     LLPBK — line loopback
// [6]     PARITY_EN
// [7]     PARITY_ODD
// [9:8]   RXBLVL — break detection level
// [31:16] NCO — baud clock rate control
#define UART_CTRL_TX_EN     BIT(0)
#define UART_CTRL_RX_EN     BIT(1)
#define UART_CTRL_NF_EN     BIT(2)
#define UART_CTRL_NCO_SHIFT 16

// ---------------------------------------------------------------------------
// STATUS register bit definitions
// ---------------------------------------------------------------------------
// [0] TXFULL   — TX buffer full
// [1] RXFULL   — RX buffer full
// [2] TXEMPTY  — TX FIFO empty
// [3] TXIDLE   — TX idle (FIFO empty + no ongoing TX)
// [4] RXIDLE   — RX idle
// [5] RXEMPTY  — RX FIFO empty
#define UART_STATUS_TXFULL   BIT(0)
#define UART_STATUS_RXFULL   BIT(1)
#define UART_STATUS_TXEMPTY  BIT(2)
#define UART_STATUS_TXIDLE   BIT(3)
#define UART_STATUS_RXIDLE   BIT(4)
#define UART_STATUS_RXEMPTY  BIT(5)

// ---------------------------------------------------------------------------
// FIFO_CTRL register bit definitions
// ---------------------------------------------------------------------------
#define UART_FIFO_CTRL_RXRST BIT(0)
#define UART_FIFO_CTRL_TXRST BIT(1)

// Base address shorthand
#define UART_BASE SAFEROOT_UART0_BASE

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

hal_status_t uart_init(uint32_t baud_rate, uint32_t clk_freq_hz) {
    if (baud_rate == 0 || clk_freq_hz == 0) {
        return kHalBadArg;
    }

    // Compute NCO value.
    // OpenTitan formula: NCO = (2^20 * baud_rate) / clk_freq
    // Avoid 64-bit division (needs libgcc). Use: NCO = baud / (clk >> 20)
    // 115200 @ 100MHz: 115200 / (100000000 >> 20) = 115200 / 95 = 1212
    uint32_t nco = baud_rate / (clk_freq_hz >> 20);
    if (nco == 0) {
        return kHalBadArg;
    }

    // Reset FIFOs
    REG32_WRITE(UART_BASE + UART_FIFO_CTRL,
                UART_FIFO_CTRL_RXRST | UART_FIFO_CTRL_TXRST);

    // Clear any pending interrupts
    REG32_WRITE(UART_BASE + UART_INTR_STATE, 0xFFFFFFFF);

    // Disable all interrupts (polling mode)
    REG32_WRITE(UART_BASE + UART_INTR_ENABLE, 0);

    // Configure: TX enable, RX enable, noise filter, NCO
    uint32_t ctrl = UART_CTRL_TX_EN | UART_CTRL_RX_EN | UART_CTRL_NF_EN |
                    (nco << UART_CTRL_NCO_SHIFT);
    REG32_WRITE(UART_BASE + UART_CTRL, ctrl);

    return kHalOk;
}

bool uart_tx_ready(void) {
    return (REG32_READ(UART_BASE + UART_STATUS) & UART_STATUS_TXFULL) == 0;
}

bool uart_rx_available(void) {
    return (REG32_READ(UART_BASE + UART_STATUS) & UART_STATUS_RXEMPTY) == 0;
}

void uart_putc(char c) {
    // Wait until TX FIFO is not full
    while (REG32_READ(UART_BASE + UART_STATUS) & UART_STATUS_TXFULL) {
        // spin
    }
    REG32_WRITE(UART_BASE + UART_WDATA, (uint32_t)(uint8_t)c);
}

void uart_puts(const char *s) {
    while (*s) {
        uart_putc(*s++);
    }
}

char uart_getc(void) {
    // Wait until RX FIFO is not empty
    while (REG32_READ(UART_BASE + UART_STATUS) & UART_STATUS_RXEMPTY) {
        // spin
    }
    return (char)(REG32_READ(UART_BASE + UART_RDATA) & 0xFF);
}

void uart_put_hex(uint32_t val) {
    static const char hex_chars[] = "0123456789abcdef";
    uart_puts("0x");
    for (int i = 28; i >= 0; i -= 4) {
        uart_putc(hex_chars[(val >> i) & 0xF]);
    }
}
