// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__xbar_connect generated by `tlgen.py` tool

xbar_main dut();

`DRIVE_CLK(clk_main_i)
`DRIVE_CLK(clk_fixed_i)

initial force dut.clk_main_i = clk_main_i;
initial force dut.clk_fixed_i = clk_fixed_i;

// TODO, all resets tie together
initial force dut.rst_main_ni = rst_n;
initial force dut.rst_fixed_ni = rst_n;

// Host TileLink interface connections
`CONNECT_TL_HOST_IF(rv_core_ibex__corei, dut, clk_main_i, rst_n)
`CONNECT_TL_HOST_IF(rv_core_ibex__cored, dut, clk_main_i, rst_n)

// Device TileLink interface connections
`CONNECT_TL_DEVICE_IF(rom_ctrl__rom, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(rom_ctrl__regs, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(sram_ctrl__regs, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(sram_ctrl__ram, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(flash_ctrl__core, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(flash_ctrl__prim, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(flash_ctrl__mem, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(aes, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(hmac, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(kmac, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(csrng, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(entropy_src, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(edn0, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(otbn, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(keymgr, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(lc_ctrl__regs, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(alert_handler, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(otp_ctrl__core, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(otp_macro__prim, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(sensor_ctrl, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(spi_device, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(gpio, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(i2c0, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(uart0, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(rv_plic, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(rv_timer, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(aon_timer_aon, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(pwrmgr_aon, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(clkmgr_aon, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(rstmgr_aon, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(pinmux_aon, dut, clk_fixed_i, rst_n)
`CONNECT_TL_DEVICE_IF(rv_core_ibex__cfg, dut, clk_main_i, rst_n)
