// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// ------------------- W A R N I N G: A U T O - G E N E R A T E D   C O D E !! -------------------//
// PLEASE DO NOT HAND-EDIT THIS FILE. IT HAS BEEN AUTO-GENERATED WITH THE FOLLOWING COMMAND:
// util/topgen.py -t hw/top_saferoot/data/top_saferoot.hjson
//                -o hw/top_saferoot/

#include "hw/top_saferoot/sw/autogen/top_saferoot.h"

/**
 * Alert Handler Alert Source to Peripheral Map
 *
 * This array is a mapping from `top_saferoot_alert_id_t` to
 * `top_saferoot_alert_peripheral_t`.
 */
const top_saferoot_alert_peripheral_t
    top_saferoot_alert_for_peripheral[49] = {
  [kTopSaferootAlertIdAesRecovCtrlUpdateErr] = kTopSaferootAlertPeripheralAes,
  [kTopSaferootAlertIdAesFatalFault] = kTopSaferootAlertPeripheralAes,
  [kTopSaferootAlertIdHmacFatalFault] = kTopSaferootAlertPeripheralHmac,
  [kTopSaferootAlertIdKmacRecovOperationErr] = kTopSaferootAlertPeripheralKmac,
  [kTopSaferootAlertIdKmacFatalFaultErr] = kTopSaferootAlertPeripheralKmac,
  [kTopSaferootAlertIdCsrngRecovAlert] = kTopSaferootAlertPeripheralCsrng,
  [kTopSaferootAlertIdCsrngFatalAlert] = kTopSaferootAlertPeripheralCsrng,
  [kTopSaferootAlertIdEntropySrcRecovAlert] = kTopSaferootAlertPeripheralEntropySrc,
  [kTopSaferootAlertIdEntropySrcFatalAlert] = kTopSaferootAlertPeripheralEntropySrc,
  [kTopSaferootAlertIdEdn0RecovAlert] = kTopSaferootAlertPeripheralEdn0,
  [kTopSaferootAlertIdEdn0FatalAlert] = kTopSaferootAlertPeripheralEdn0,
  [kTopSaferootAlertIdOtbnFatal] = kTopSaferootAlertPeripheralOtbn,
  [kTopSaferootAlertIdOtbnRecov] = kTopSaferootAlertPeripheralOtbn,
  [kTopSaferootAlertIdKeymgrRecovOperationErr] = kTopSaferootAlertPeripheralKeymgr,
  [kTopSaferootAlertIdKeymgrFatalFaultErr] = kTopSaferootAlertPeripheralKeymgr,
  [kTopSaferootAlertIdLcCtrlFatalProgError] = kTopSaferootAlertPeripheralLcCtrl,
  [kTopSaferootAlertIdLcCtrlFatalStateError] = kTopSaferootAlertPeripheralLcCtrl,
  [kTopSaferootAlertIdLcCtrlFatalBusIntegError] = kTopSaferootAlertPeripheralLcCtrl,
  [kTopSaferootAlertIdOtpCtrlFatalMacroError] = kTopSaferootAlertPeripheralOtpCtrl,
  [kTopSaferootAlertIdOtpCtrlFatalCheckError] = kTopSaferootAlertPeripheralOtpCtrl,
  [kTopSaferootAlertIdOtpCtrlFatalBusIntegError] = kTopSaferootAlertPeripheralOtpCtrl,
  [kTopSaferootAlertIdOtpCtrlFatalPrimOtpAlert] = kTopSaferootAlertPeripheralOtpCtrl,
  [kTopSaferootAlertIdOtpCtrlRecovPrimOtpAlert] = kTopSaferootAlertPeripheralOtpCtrl,
  [kTopSaferootAlertIdSensorCtrlRecovAlert] = kTopSaferootAlertPeripheralSensorCtrl,
  [kTopSaferootAlertIdSensorCtrlFatalAlert] = kTopSaferootAlertPeripheralSensorCtrl,
  [kTopSaferootAlertIdSpiDeviceFatalFault] = kTopSaferootAlertPeripheralSpiDevice,
  [kTopSaferootAlertIdGpioFatalFault] = kTopSaferootAlertPeripheralGpio,
  [kTopSaferootAlertIdI2c0FatalFault] = kTopSaferootAlertPeripheralI2c0,
  [kTopSaferootAlertIdUart0FatalFault] = kTopSaferootAlertPeripheralUart0,
  [kTopSaferootAlertIdRvPlicFatalFault] = kTopSaferootAlertPeripheralRvPlic,
  [kTopSaferootAlertIdRvTimerFatalFault] = kTopSaferootAlertPeripheralRvTimer,
  [kTopSaferootAlertIdAonTimerAonFatalFault] = kTopSaferootAlertPeripheralAonTimerAon,
  [kTopSaferootAlertIdPwrmgrAonFatalFault] = kTopSaferootAlertPeripheralPwrmgrAon,
  [kTopSaferootAlertIdClkmgrAonRecovFault] = kTopSaferootAlertPeripheralClkmgrAon,
  [kTopSaferootAlertIdClkmgrAonFatalFault] = kTopSaferootAlertPeripheralClkmgrAon,
  [kTopSaferootAlertIdRstmgrAonFatalFault] = kTopSaferootAlertPeripheralRstmgrAon,
  [kTopSaferootAlertIdRstmgrAonFatalCnstyFault] = kTopSaferootAlertPeripheralRstmgrAon,
  [kTopSaferootAlertIdPinmuxAonFatalFault] = kTopSaferootAlertPeripheralPinmuxAon,
  [kTopSaferootAlertIdRomCtrlFatal] = kTopSaferootAlertPeripheralRomCtrl,
  [kTopSaferootAlertIdSramCtrlFatalError] = kTopSaferootAlertPeripheralSramCtrl,
  [kTopSaferootAlertIdFlashCtrlRecovErr] = kTopSaferootAlertPeripheralFlashCtrl,
  [kTopSaferootAlertIdFlashCtrlFatalStdErr] = kTopSaferootAlertPeripheralFlashCtrl,
  [kTopSaferootAlertIdFlashCtrlFatalErr] = kTopSaferootAlertPeripheralFlashCtrl,
  [kTopSaferootAlertIdFlashCtrlFatalPrimFlashAlert] = kTopSaferootAlertPeripheralFlashCtrl,
  [kTopSaferootAlertIdFlashCtrlRecovPrimFlashAlert] = kTopSaferootAlertPeripheralFlashCtrl,
  [kTopSaferootAlertIdRvCoreIbexFatalSwErr] = kTopSaferootAlertPeripheralRvCoreIbex,
  [kTopSaferootAlertIdRvCoreIbexRecovSwErr] = kTopSaferootAlertPeripheralRvCoreIbex,
  [kTopSaferootAlertIdRvCoreIbexFatalHwErr] = kTopSaferootAlertPeripheralRvCoreIbex,
  [kTopSaferootAlertIdRvCoreIbexRecovHwErr] = kTopSaferootAlertPeripheralRvCoreIbex,
};

/**
 * PLIC Interrupt Source to Peripheral Map
 *
 * This array is a mapping from `top_saferoot_plic_irq_id_t` to
 * `top_saferoot_plic_peripheral_t`.
 */
const top_saferoot_plic_peripheral_t
    top_saferoot_plic_interrupt_for_peripheral[101] = {
  [kTopSaferootPlicIrqIdNone] = kTopSaferootPlicPeripheralUnknown,
  [kTopSaferootPlicIrqIdHmacHmacDone] = kTopSaferootPlicPeripheralHmac,
  [kTopSaferootPlicIrqIdHmacFifoEmpty] = kTopSaferootPlicPeripheralHmac,
  [kTopSaferootPlicIrqIdHmacHmacErr] = kTopSaferootPlicPeripheralHmac,
  [kTopSaferootPlicIrqIdKmacKmacDone] = kTopSaferootPlicPeripheralKmac,
  [kTopSaferootPlicIrqIdKmacFifoEmpty] = kTopSaferootPlicPeripheralKmac,
  [kTopSaferootPlicIrqIdKmacKmacErr] = kTopSaferootPlicPeripheralKmac,
  [kTopSaferootPlicIrqIdCsrngCsCmdReqDone] = kTopSaferootPlicPeripheralCsrng,
  [kTopSaferootPlicIrqIdCsrngCsEntropyReq] = kTopSaferootPlicPeripheralCsrng,
  [kTopSaferootPlicIrqIdCsrngCsHwInstExc] = kTopSaferootPlicPeripheralCsrng,
  [kTopSaferootPlicIrqIdCsrngCsFatalErr] = kTopSaferootPlicPeripheralCsrng,
  [kTopSaferootPlicIrqIdEntropySrcEsEntropyValid] = kTopSaferootPlicPeripheralEntropySrc,
  [kTopSaferootPlicIrqIdEntropySrcEsHealthTestFailed] = kTopSaferootPlicPeripheralEntropySrc,
  [kTopSaferootPlicIrqIdEntropySrcEsObserveFifoReady] = kTopSaferootPlicPeripheralEntropySrc,
  [kTopSaferootPlicIrqIdEntropySrcEsFatalErr] = kTopSaferootPlicPeripheralEntropySrc,
  [kTopSaferootPlicIrqIdEdn0EdnCmdReqDone] = kTopSaferootPlicPeripheralEdn0,
  [kTopSaferootPlicIrqIdEdn0EdnFatalErr] = kTopSaferootPlicPeripheralEdn0,
  [kTopSaferootPlicIrqIdOtbnDone] = kTopSaferootPlicPeripheralOtbn,
  [kTopSaferootPlicIrqIdKeymgrOpDone] = kTopSaferootPlicPeripheralKeymgr,
  [kTopSaferootPlicIrqIdAlertHandlerClassa] = kTopSaferootPlicPeripheralAlertHandler,
  [kTopSaferootPlicIrqIdAlertHandlerClassb] = kTopSaferootPlicPeripheralAlertHandler,
  [kTopSaferootPlicIrqIdAlertHandlerClassc] = kTopSaferootPlicPeripheralAlertHandler,
  [kTopSaferootPlicIrqIdAlertHandlerClassd] = kTopSaferootPlicPeripheralAlertHandler,
  [kTopSaferootPlicIrqIdOtpCtrlOtpOperationDone] = kTopSaferootPlicPeripheralOtpCtrl,
  [kTopSaferootPlicIrqIdOtpCtrlOtpError] = kTopSaferootPlicPeripheralOtpCtrl,
  [kTopSaferootPlicIrqIdSensorCtrlIoStatusChange] = kTopSaferootPlicPeripheralSensorCtrl,
  [kTopSaferootPlicIrqIdSensorCtrlInitStatusChange] = kTopSaferootPlicPeripheralSensorCtrl,
  [kTopSaferootPlicIrqIdSpiDeviceUploadCmdfifoNotEmpty] = kTopSaferootPlicPeripheralSpiDevice,
  [kTopSaferootPlicIrqIdSpiDeviceUploadPayloadNotEmpty] = kTopSaferootPlicPeripheralSpiDevice,
  [kTopSaferootPlicIrqIdSpiDeviceUploadPayloadOverflow] = kTopSaferootPlicPeripheralSpiDevice,
  [kTopSaferootPlicIrqIdSpiDeviceReadbufWatermark] = kTopSaferootPlicPeripheralSpiDevice,
  [kTopSaferootPlicIrqIdSpiDeviceReadbufFlip] = kTopSaferootPlicPeripheralSpiDevice,
  [kTopSaferootPlicIrqIdSpiDeviceTpmHeaderNotEmpty] = kTopSaferootPlicPeripheralSpiDevice,
  [kTopSaferootPlicIrqIdSpiDeviceTpmRdfifoCmdEnd] = kTopSaferootPlicPeripheralSpiDevice,
  [kTopSaferootPlicIrqIdSpiDeviceTpmRdfifoDrop] = kTopSaferootPlicPeripheralSpiDevice,
  [kTopSaferootPlicIrqIdGpioGpio0] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio1] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio2] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio3] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio4] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio5] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio6] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio7] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio8] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio9] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio10] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio11] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio12] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio13] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio14] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio15] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio16] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio17] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio18] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio19] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio20] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio21] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio22] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio23] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio24] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio25] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio26] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio27] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio28] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio29] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio30] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdGpioGpio31] = kTopSaferootPlicPeripheralGpio,
  [kTopSaferootPlicIrqIdI2c0FmtThreshold] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0RxThreshold] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0AcqThreshold] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0RxOverflow] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0ControllerHalt] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0SclInterference] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0SdaInterference] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0StretchTimeout] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0SdaUnstable] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0CmdComplete] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0TxStretch] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0TxThreshold] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0AcqStretch] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0UnexpStop] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdI2c0HostTimeout] = kTopSaferootPlicPeripheralI2c0,
  [kTopSaferootPlicIrqIdUart0TxWatermark] = kTopSaferootPlicPeripheralUart0,
  [kTopSaferootPlicIrqIdUart0RxWatermark] = kTopSaferootPlicPeripheralUart0,
  [kTopSaferootPlicIrqIdUart0TxDone] = kTopSaferootPlicPeripheralUart0,
  [kTopSaferootPlicIrqIdUart0RxOverflow] = kTopSaferootPlicPeripheralUart0,
  [kTopSaferootPlicIrqIdUart0RxFrameErr] = kTopSaferootPlicPeripheralUart0,
  [kTopSaferootPlicIrqIdUart0RxBreakErr] = kTopSaferootPlicPeripheralUart0,
  [kTopSaferootPlicIrqIdUart0RxTimeout] = kTopSaferootPlicPeripheralUart0,
  [kTopSaferootPlicIrqIdUart0RxParityErr] = kTopSaferootPlicPeripheralUart0,
  [kTopSaferootPlicIrqIdUart0TxEmpty] = kTopSaferootPlicPeripheralUart0,
  [kTopSaferootPlicIrqIdRvTimerTimerExpiredHart0Timer0] = kTopSaferootPlicPeripheralRvTimer,
  [kTopSaferootPlicIrqIdAonTimerAonWkupTimerExpired] = kTopSaferootPlicPeripheralAonTimerAon,
  [kTopSaferootPlicIrqIdAonTimerAonWdogTimerBark] = kTopSaferootPlicPeripheralAonTimerAon,
  [kTopSaferootPlicIrqIdPwrmgrAonWakeup] = kTopSaferootPlicPeripheralPwrmgrAon,
  [kTopSaferootPlicIrqIdFlashCtrlProgEmpty] = kTopSaferootPlicPeripheralFlashCtrl,
  [kTopSaferootPlicIrqIdFlashCtrlProgLvl] = kTopSaferootPlicPeripheralFlashCtrl,
  [kTopSaferootPlicIrqIdFlashCtrlRdFull] = kTopSaferootPlicPeripheralFlashCtrl,
  [kTopSaferootPlicIrqIdFlashCtrlRdLvl] = kTopSaferootPlicPeripheralFlashCtrl,
  [kTopSaferootPlicIrqIdFlashCtrlOpDone] = kTopSaferootPlicPeripheralFlashCtrl,
  [kTopSaferootPlicIrqIdFlashCtrlCorrErr] = kTopSaferootPlicPeripheralFlashCtrl,
};
