// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// This file was generated automatically.
// Please do not modify content of this file directly.
// File generated by using template: "toplevel.rs.tpl"
// To regenerate this file follow OpenTitan topgen documentations.

#![allow(dead_code)]

//! This file contains enums and consts for use within the Rust codebase.
//!
//! These definitions are for information that depends on the top-specific chip
//! configuration, which includes:
//! - Device Memory Information (for Peripherals and Memory)
//! - PLIC Interrupt ID Names and Source Mappings
//! - Alert ID Names and Source Mappings
//! - Pinmux Pin/Select Names
//! - Power Manager Wakeups

use core::convert::TryFrom;

/// Peripheral base address for aes in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const AES_BASE_ADDR: usize = 0x40000000;

/// Peripheral size for aes in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #AES_BASE_ADDR and
/// `AES_BASE_ADDR + AES_SIZE_BYTES`.
pub const AES_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for hmac in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const HMAC_BASE_ADDR: usize = 0x40010000;

/// Peripheral size for hmac in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #HMAC_BASE_ADDR and
/// `HMAC_BASE_ADDR + HMAC_SIZE_BYTES`.
pub const HMAC_SIZE_BYTES: usize = 0x2000;

/// Peripheral base address for kmac in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const KMAC_BASE_ADDR: usize = 0x40020000;

/// Peripheral size for kmac in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #KMAC_BASE_ADDR and
/// `KMAC_BASE_ADDR + KMAC_SIZE_BYTES`.
pub const KMAC_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for csrng in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const CSRNG_BASE_ADDR: usize = 0x40030000;

/// Peripheral size for csrng in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #CSRNG_BASE_ADDR and
/// `CSRNG_BASE_ADDR + CSRNG_SIZE_BYTES`.
pub const CSRNG_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for entropy_src in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ENTROPY_SRC_BASE_ADDR: usize = 0x40040000;

/// Peripheral size for entropy_src in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ENTROPY_SRC_BASE_ADDR and
/// `ENTROPY_SRC_BASE_ADDR + ENTROPY_SRC_SIZE_BYTES`.
pub const ENTROPY_SRC_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for edn0 in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const EDN0_BASE_ADDR: usize = 0x40005000;

/// Peripheral size for edn0 in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #EDN0_BASE_ADDR and
/// `EDN0_BASE_ADDR + EDN0_SIZE_BYTES`.
pub const EDN0_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for otbn in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTBN_BASE_ADDR: usize = 0x40080000;

/// Peripheral size for otbn in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTBN_BASE_ADDR and
/// `OTBN_BASE_ADDR + OTBN_SIZE_BYTES`.
pub const OTBN_SIZE_BYTES: usize = 0x10000;

/// Peripheral base address for keymgr in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const KEYMGR_BASE_ADDR: usize = 0x40100000;

/// Peripheral size for keymgr in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #KEYMGR_BASE_ADDR and
/// `KEYMGR_BASE_ADDR + KEYMGR_SIZE_BYTES`.
pub const KEYMGR_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for regs device on lc_ctrl in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const LC_CTRL_REGS_BASE_ADDR: usize = 0x40101000;

/// Peripheral size for regs device on lc_ctrl in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #LC_CTRL_REGS_BASE_ADDR and
/// `LC_CTRL_REGS_BASE_ADDR + LC_CTRL_REGS_SIZE_BYTES`.
pub const LC_CTRL_REGS_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for dmi device on lc_ctrl in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const LC_CTRL_DMI_BASE_ADDR: usize = 0x0;

/// Peripheral size for dmi device on lc_ctrl in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #LC_CTRL_DMI_BASE_ADDR and
/// `LC_CTRL_DMI_BASE_ADDR + LC_CTRL_DMI_SIZE_BYTES`.
pub const LC_CTRL_DMI_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for alert_handler in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ALERT_HANDLER_BASE_ADDR: usize = 0x40120000;

/// Peripheral size for alert_handler in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ALERT_HANDLER_BASE_ADDR and
/// `ALERT_HANDLER_BASE_ADDR + ALERT_HANDLER_SIZE_BYTES`.
pub const ALERT_HANDLER_SIZE_BYTES: usize = 0x800;

/// Peripheral base address for core device on otp_ctrl in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTP_CTRL_CORE_BASE_ADDR: usize = 0x40130000;

/// Peripheral size for core device on otp_ctrl in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTP_CTRL_CORE_BASE_ADDR and
/// `OTP_CTRL_CORE_BASE_ADDR + OTP_CTRL_CORE_SIZE_BYTES`.
pub const OTP_CTRL_CORE_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for prim device on otp_macro in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTP_MACRO_PRIM_BASE_ADDR: usize = 0x40138000;

/// Peripheral size for prim device on otp_macro in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTP_MACRO_PRIM_BASE_ADDR and
/// `OTP_MACRO_PRIM_BASE_ADDR + OTP_MACRO_PRIM_SIZE_BYTES`.
pub const OTP_MACRO_PRIM_SIZE_BYTES: usize = 0x20;

/// Peripheral base address for sensor_ctrl in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SENSOR_CTRL_BASE_ADDR: usize = 0x40140000;

/// Peripheral size for sensor_ctrl in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SENSOR_CTRL_BASE_ADDR and
/// `SENSOR_CTRL_BASE_ADDR + SENSOR_CTRL_SIZE_BYTES`.
pub const SENSOR_CTRL_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for spi_device in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SPI_DEVICE_BASE_ADDR: usize = 0x40200000;

/// Peripheral size for spi_device in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SPI_DEVICE_BASE_ADDR and
/// `SPI_DEVICE_BASE_ADDR + SPI_DEVICE_SIZE_BYTES`.
pub const SPI_DEVICE_SIZE_BYTES: usize = 0x2000;

/// Peripheral base address for gpio in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const GPIO_BASE_ADDR: usize = 0x40210000;

/// Peripheral size for gpio in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #GPIO_BASE_ADDR and
/// `GPIO_BASE_ADDR + GPIO_SIZE_BYTES`.
pub const GPIO_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for i2c0 in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const I2C0_BASE_ADDR: usize = 0x40220000;

/// Peripheral size for i2c0 in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #I2C0_BASE_ADDR and
/// `I2C0_BASE_ADDR + I2C0_SIZE_BYTES`.
pub const I2C0_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for uart0 in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const UART0_BASE_ADDR: usize = 0x40230000;

/// Peripheral size for uart0 in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #UART0_BASE_ADDR and
/// `UART0_BASE_ADDR + UART0_SIZE_BYTES`.
pub const UART0_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for rv_plic in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_PLIC_BASE_ADDR: usize = 0x48000000;

/// Peripheral size for rv_plic in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_PLIC_BASE_ADDR and
/// `RV_PLIC_BASE_ADDR + RV_PLIC_SIZE_BYTES`.
pub const RV_PLIC_SIZE_BYTES: usize = 0x8000000;

/// Peripheral base address for rv_timer in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_TIMER_BASE_ADDR: usize = 0x40310000;

/// Peripheral size for rv_timer in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_TIMER_BASE_ADDR and
/// `RV_TIMER_BASE_ADDR + RV_TIMER_SIZE_BYTES`.
pub const RV_TIMER_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for aon_timer_aon in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const AON_TIMER_AON_BASE_ADDR: usize = 0x40320000;

/// Peripheral size for aon_timer_aon in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #AON_TIMER_AON_BASE_ADDR and
/// `AON_TIMER_AON_BASE_ADDR + AON_TIMER_AON_SIZE_BYTES`.
pub const AON_TIMER_AON_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for pwrmgr_aon in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PWRMGR_AON_BASE_ADDR: usize = 0x40330000;

/// Peripheral size for pwrmgr_aon in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PWRMGR_AON_BASE_ADDR and
/// `PWRMGR_AON_BASE_ADDR + PWRMGR_AON_SIZE_BYTES`.
pub const PWRMGR_AON_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for clkmgr_aon in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const CLKMGR_AON_BASE_ADDR: usize = 0x40340000;

/// Peripheral size for clkmgr_aon in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #CLKMGR_AON_BASE_ADDR and
/// `CLKMGR_AON_BASE_ADDR + CLKMGR_AON_SIZE_BYTES`.
pub const CLKMGR_AON_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for rstmgr_aon in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RSTMGR_AON_BASE_ADDR: usize = 0x40350000;

/// Peripheral size for rstmgr_aon in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RSTMGR_AON_BASE_ADDR and
/// `RSTMGR_AON_BASE_ADDR + RSTMGR_AON_SIZE_BYTES`.
pub const RSTMGR_AON_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for pinmux_aon in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PINMUX_AON_BASE_ADDR: usize = 0x40360000;

/// Peripheral size for pinmux_aon in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PINMUX_AON_BASE_ADDR and
/// `PINMUX_AON_BASE_ADDR + PINMUX_AON_SIZE_BYTES`.
pub const PINMUX_AON_SIZE_BYTES: usize = 0x400;

/// Peripheral base address for regs device on rom_ctrl in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ROM_CTRL_REGS_BASE_ADDR: usize = 0x40007000;

/// Peripheral size for regs device on rom_ctrl in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ROM_CTRL_REGS_BASE_ADDR and
/// `ROM_CTRL_REGS_BASE_ADDR + ROM_CTRL_REGS_SIZE_BYTES`.
pub const ROM_CTRL_REGS_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for regs device on sram_ctrl in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_REGS_BASE_ADDR: usize = 0x40008000;

/// Peripheral size for regs device on sram_ctrl in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_REGS_BASE_ADDR and
/// `SRAM_CTRL_REGS_BASE_ADDR + SRAM_CTRL_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for core device on flash_ctrl in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const FLASH_CTRL_CORE_BASE_ADDR: usize = 0x40009000;

/// Peripheral size for core device on flash_ctrl in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #FLASH_CTRL_CORE_BASE_ADDR and
/// `FLASH_CTRL_CORE_BASE_ADDR + FLASH_CTRL_CORE_SIZE_BYTES`.
pub const FLASH_CTRL_CORE_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for prim device on flash_ctrl in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const FLASH_CTRL_PRIM_BASE_ADDR: usize = 0x4000A000;

/// Peripheral size for prim device on flash_ctrl in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #FLASH_CTRL_PRIM_BASE_ADDR and
/// `FLASH_CTRL_PRIM_BASE_ADDR + FLASH_CTRL_PRIM_SIZE_BYTES`.
pub const FLASH_CTRL_PRIM_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for cfg device on rv_core_ibex in top saferoot.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_CORE_IBEX_CFG_BASE_ADDR: usize = 0x4000B000;

/// Peripheral size for cfg device on rv_core_ibex in top saferoot.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_CORE_IBEX_CFG_BASE_ADDR and
/// `RV_CORE_IBEX_CFG_BASE_ADDR + RV_CORE_IBEX_CFG_SIZE_BYTES`.
pub const RV_CORE_IBEX_CFG_SIZE_BYTES: usize = 0x100;

/// Memory base address for rom memory on rom_ctrl in top saferoot.
pub const ROM_CTRL_ROM_BASE_ADDR: usize = 0x0;

/// Memory size for rom memory on rom_ctrl in top saferoot.
pub const ROM_CTRL_ROM_SIZE_BYTES: usize = 0x8000;

/// Memory base address for ram memory on sram_ctrl in top saferoot.
pub const SRAM_CTRL_RAM_BASE_ADDR: usize = 0x10000000;

/// Memory size for ram memory on sram_ctrl in top saferoot.
pub const SRAM_CTRL_RAM_SIZE_BYTES: usize = 0x20000;

/// Memory base address for mem memory on flash_ctrl in top saferoot.
pub const FLASH_CTRL_MEM_BASE_ADDR: usize = 0x20000000;

/// Memory size for mem memory on flash_ctrl in top saferoot.
pub const FLASH_CTRL_MEM_SIZE_BYTES: usize = 0x100000;

/// PLIC Interrupt Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// interrupt.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicPeripheral {
    /// Unknown Peripheral
    Unknown = 0,
    /// hmac
    Hmac = 1,
    /// kmac
    Kmac = 2,
    /// csrng
    Csrng = 3,
    /// entropy_src
    EntropySrc = 4,
    /// edn0
    Edn0 = 5,
    /// otbn
    Otbn = 6,
    /// keymgr
    Keymgr = 7,
    /// alert_handler
    AlertHandler = 8,
    /// otp_ctrl
    OtpCtrl = 9,
    /// sensor_ctrl
    SensorCtrl = 10,
    /// spi_device
    SpiDevice = 11,
    /// gpio
    Gpio = 12,
    /// i2c0
    I2c0 = 13,
    /// uart0
    Uart0 = 14,
    /// rv_timer
    RvTimer = 15,
    /// aon_timer_aon
    AonTimerAon = 16,
    /// pwrmgr_aon
    PwrmgrAon = 17,
    /// flash_ctrl
    FlashCtrl = 18,
}

impl TryFrom<u32> for PlicPeripheral {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Unknown),
            1 => Ok(Self::Hmac),
            2 => Ok(Self::Kmac),
            3 => Ok(Self::Csrng),
            4 => Ok(Self::EntropySrc),
            5 => Ok(Self::Edn0),
            6 => Ok(Self::Otbn),
            7 => Ok(Self::Keymgr),
            8 => Ok(Self::AlertHandler),
            9 => Ok(Self::OtpCtrl),
            10 => Ok(Self::SensorCtrl),
            11 => Ok(Self::SpiDevice),
            12 => Ok(Self::Gpio),
            13 => Ok(Self::I2c0),
            14 => Ok(Self::Uart0),
            15 => Ok(Self::RvTimer),
            16 => Ok(Self::AonTimerAon),
            17 => Ok(Self::PwrmgrAon),
            18 => Ok(Self::FlashCtrl),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Source.
///
/// Enumeration of all PLIC interrupt sources. The interrupt sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicIrqId {
    /// No Interrupt
    None = 0,
    /// hmac_hmac_done
    HmacHmacDone = 1,
    /// hmac_fifo_empty
    HmacFifoEmpty = 2,
    /// hmac_hmac_err
    HmacHmacErr = 3,
    /// kmac_kmac_done
    KmacKmacDone = 4,
    /// kmac_fifo_empty
    KmacFifoEmpty = 5,
    /// kmac_kmac_err
    KmacKmacErr = 6,
    /// csrng_cs_cmd_req_done
    CsrngCsCmdReqDone = 7,
    /// csrng_cs_entropy_req
    CsrngCsEntropyReq = 8,
    /// csrng_cs_hw_inst_exc
    CsrngCsHwInstExc = 9,
    /// csrng_cs_fatal_err
    CsrngCsFatalErr = 10,
    /// entropy_src_es_entropy_valid
    EntropySrcEsEntropyValid = 11,
    /// entropy_src_es_health_test_failed
    EntropySrcEsHealthTestFailed = 12,
    /// entropy_src_es_observe_fifo_ready
    EntropySrcEsObserveFifoReady = 13,
    /// entropy_src_es_fatal_err
    EntropySrcEsFatalErr = 14,
    /// edn0_edn_cmd_req_done
    Edn0EdnCmdReqDone = 15,
    /// edn0_edn_fatal_err
    Edn0EdnFatalErr = 16,
    /// otbn_done
    OtbnDone = 17,
    /// keymgr_op_done
    KeymgrOpDone = 18,
    /// alert_handler_classa
    AlertHandlerClassa = 19,
    /// alert_handler_classb
    AlertHandlerClassb = 20,
    /// alert_handler_classc
    AlertHandlerClassc = 21,
    /// alert_handler_classd
    AlertHandlerClassd = 22,
    /// otp_ctrl_otp_operation_done
    OtpCtrlOtpOperationDone = 23,
    /// otp_ctrl_otp_error
    OtpCtrlOtpError = 24,
    /// sensor_ctrl_io_status_change
    SensorCtrlIoStatusChange = 25,
    /// sensor_ctrl_init_status_change
    SensorCtrlInitStatusChange = 26,
    /// spi_device_upload_cmdfifo_not_empty
    SpiDeviceUploadCmdfifoNotEmpty = 27,
    /// spi_device_upload_payload_not_empty
    SpiDeviceUploadPayloadNotEmpty = 28,
    /// spi_device_upload_payload_overflow
    SpiDeviceUploadPayloadOverflow = 29,
    /// spi_device_readbuf_watermark
    SpiDeviceReadbufWatermark = 30,
    /// spi_device_readbuf_flip
    SpiDeviceReadbufFlip = 31,
    /// spi_device_tpm_header_not_empty
    SpiDeviceTpmHeaderNotEmpty = 32,
    /// spi_device_tpm_rdfifo_cmd_end
    SpiDeviceTpmRdfifoCmdEnd = 33,
    /// spi_device_tpm_rdfifo_drop
    SpiDeviceTpmRdfifoDrop = 34,
    /// gpio_gpio 0
    GpioGpio0 = 35,
    /// gpio_gpio 1
    GpioGpio1 = 36,
    /// gpio_gpio 2
    GpioGpio2 = 37,
    /// gpio_gpio 3
    GpioGpio3 = 38,
    /// gpio_gpio 4
    GpioGpio4 = 39,
    /// gpio_gpio 5
    GpioGpio5 = 40,
    /// gpio_gpio 6
    GpioGpio6 = 41,
    /// gpio_gpio 7
    GpioGpio7 = 42,
    /// gpio_gpio 8
    GpioGpio8 = 43,
    /// gpio_gpio 9
    GpioGpio9 = 44,
    /// gpio_gpio 10
    GpioGpio10 = 45,
    /// gpio_gpio 11
    GpioGpio11 = 46,
    /// gpio_gpio 12
    GpioGpio12 = 47,
    /// gpio_gpio 13
    GpioGpio13 = 48,
    /// gpio_gpio 14
    GpioGpio14 = 49,
    /// gpio_gpio 15
    GpioGpio15 = 50,
    /// gpio_gpio 16
    GpioGpio16 = 51,
    /// gpio_gpio 17
    GpioGpio17 = 52,
    /// gpio_gpio 18
    GpioGpio18 = 53,
    /// gpio_gpio 19
    GpioGpio19 = 54,
    /// gpio_gpio 20
    GpioGpio20 = 55,
    /// gpio_gpio 21
    GpioGpio21 = 56,
    /// gpio_gpio 22
    GpioGpio22 = 57,
    /// gpio_gpio 23
    GpioGpio23 = 58,
    /// gpio_gpio 24
    GpioGpio24 = 59,
    /// gpio_gpio 25
    GpioGpio25 = 60,
    /// gpio_gpio 26
    GpioGpio26 = 61,
    /// gpio_gpio 27
    GpioGpio27 = 62,
    /// gpio_gpio 28
    GpioGpio28 = 63,
    /// gpio_gpio 29
    GpioGpio29 = 64,
    /// gpio_gpio 30
    GpioGpio30 = 65,
    /// gpio_gpio 31
    GpioGpio31 = 66,
    /// i2c0_fmt_threshold
    I2c0FmtThreshold = 67,
    /// i2c0_rx_threshold
    I2c0RxThreshold = 68,
    /// i2c0_acq_threshold
    I2c0AcqThreshold = 69,
    /// i2c0_rx_overflow
    I2c0RxOverflow = 70,
    /// i2c0_controller_halt
    I2c0ControllerHalt = 71,
    /// i2c0_scl_interference
    I2c0SclInterference = 72,
    /// i2c0_sda_interference
    I2c0SdaInterference = 73,
    /// i2c0_stretch_timeout
    I2c0StretchTimeout = 74,
    /// i2c0_sda_unstable
    I2c0SdaUnstable = 75,
    /// i2c0_cmd_complete
    I2c0CmdComplete = 76,
    /// i2c0_tx_stretch
    I2c0TxStretch = 77,
    /// i2c0_tx_threshold
    I2c0TxThreshold = 78,
    /// i2c0_acq_stretch
    I2c0AcqStretch = 79,
    /// i2c0_unexp_stop
    I2c0UnexpStop = 80,
    /// i2c0_host_timeout
    I2c0HostTimeout = 81,
    /// uart0_tx_watermark
    Uart0TxWatermark = 82,
    /// uart0_rx_watermark
    Uart0RxWatermark = 83,
    /// uart0_tx_done
    Uart0TxDone = 84,
    /// uart0_rx_overflow
    Uart0RxOverflow = 85,
    /// uart0_rx_frame_err
    Uart0RxFrameErr = 86,
    /// uart0_rx_break_err
    Uart0RxBreakErr = 87,
    /// uart0_rx_timeout
    Uart0RxTimeout = 88,
    /// uart0_rx_parity_err
    Uart0RxParityErr = 89,
    /// uart0_tx_empty
    Uart0TxEmpty = 90,
    /// rv_timer_timer_expired_hart0_timer0
    RvTimerTimerExpiredHart0Timer0 = 91,
    /// aon_timer_aon_wkup_timer_expired
    AonTimerAonWkupTimerExpired = 92,
    /// aon_timer_aon_wdog_timer_bark
    AonTimerAonWdogTimerBark = 93,
    /// pwrmgr_aon_wakeup
    PwrmgrAonWakeup = 94,
    /// flash_ctrl_prog_empty
    FlashCtrlProgEmpty = 95,
    /// flash_ctrl_prog_lvl
    FlashCtrlProgLvl = 96,
    /// flash_ctrl_rd_full
    FlashCtrlRdFull = 97,
    /// flash_ctrl_rd_lvl
    FlashCtrlRdLvl = 98,
    /// flash_ctrl_op_done
    FlashCtrlOpDone = 99,
    /// flash_ctrl_corr_err
    FlashCtrlCorrErr = 100,
}

impl TryFrom<u32> for PlicIrqId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::None),
            1 => Ok(Self::HmacHmacDone),
            2 => Ok(Self::HmacFifoEmpty),
            3 => Ok(Self::HmacHmacErr),
            4 => Ok(Self::KmacKmacDone),
            5 => Ok(Self::KmacFifoEmpty),
            6 => Ok(Self::KmacKmacErr),
            7 => Ok(Self::CsrngCsCmdReqDone),
            8 => Ok(Self::CsrngCsEntropyReq),
            9 => Ok(Self::CsrngCsHwInstExc),
            10 => Ok(Self::CsrngCsFatalErr),
            11 => Ok(Self::EntropySrcEsEntropyValid),
            12 => Ok(Self::EntropySrcEsHealthTestFailed),
            13 => Ok(Self::EntropySrcEsObserveFifoReady),
            14 => Ok(Self::EntropySrcEsFatalErr),
            15 => Ok(Self::Edn0EdnCmdReqDone),
            16 => Ok(Self::Edn0EdnFatalErr),
            17 => Ok(Self::OtbnDone),
            18 => Ok(Self::KeymgrOpDone),
            19 => Ok(Self::AlertHandlerClassa),
            20 => Ok(Self::AlertHandlerClassb),
            21 => Ok(Self::AlertHandlerClassc),
            22 => Ok(Self::AlertHandlerClassd),
            23 => Ok(Self::OtpCtrlOtpOperationDone),
            24 => Ok(Self::OtpCtrlOtpError),
            25 => Ok(Self::SensorCtrlIoStatusChange),
            26 => Ok(Self::SensorCtrlInitStatusChange),
            27 => Ok(Self::SpiDeviceUploadCmdfifoNotEmpty),
            28 => Ok(Self::SpiDeviceUploadPayloadNotEmpty),
            29 => Ok(Self::SpiDeviceUploadPayloadOverflow),
            30 => Ok(Self::SpiDeviceReadbufWatermark),
            31 => Ok(Self::SpiDeviceReadbufFlip),
            32 => Ok(Self::SpiDeviceTpmHeaderNotEmpty),
            33 => Ok(Self::SpiDeviceTpmRdfifoCmdEnd),
            34 => Ok(Self::SpiDeviceTpmRdfifoDrop),
            35 => Ok(Self::GpioGpio0),
            36 => Ok(Self::GpioGpio1),
            37 => Ok(Self::GpioGpio2),
            38 => Ok(Self::GpioGpio3),
            39 => Ok(Self::GpioGpio4),
            40 => Ok(Self::GpioGpio5),
            41 => Ok(Self::GpioGpio6),
            42 => Ok(Self::GpioGpio7),
            43 => Ok(Self::GpioGpio8),
            44 => Ok(Self::GpioGpio9),
            45 => Ok(Self::GpioGpio10),
            46 => Ok(Self::GpioGpio11),
            47 => Ok(Self::GpioGpio12),
            48 => Ok(Self::GpioGpio13),
            49 => Ok(Self::GpioGpio14),
            50 => Ok(Self::GpioGpio15),
            51 => Ok(Self::GpioGpio16),
            52 => Ok(Self::GpioGpio17),
            53 => Ok(Self::GpioGpio18),
            54 => Ok(Self::GpioGpio19),
            55 => Ok(Self::GpioGpio20),
            56 => Ok(Self::GpioGpio21),
            57 => Ok(Self::GpioGpio22),
            58 => Ok(Self::GpioGpio23),
            59 => Ok(Self::GpioGpio24),
            60 => Ok(Self::GpioGpio25),
            61 => Ok(Self::GpioGpio26),
            62 => Ok(Self::GpioGpio27),
            63 => Ok(Self::GpioGpio28),
            64 => Ok(Self::GpioGpio29),
            65 => Ok(Self::GpioGpio30),
            66 => Ok(Self::GpioGpio31),
            67 => Ok(Self::I2c0FmtThreshold),
            68 => Ok(Self::I2c0RxThreshold),
            69 => Ok(Self::I2c0AcqThreshold),
            70 => Ok(Self::I2c0RxOverflow),
            71 => Ok(Self::I2c0ControllerHalt),
            72 => Ok(Self::I2c0SclInterference),
            73 => Ok(Self::I2c0SdaInterference),
            74 => Ok(Self::I2c0StretchTimeout),
            75 => Ok(Self::I2c0SdaUnstable),
            76 => Ok(Self::I2c0CmdComplete),
            77 => Ok(Self::I2c0TxStretch),
            78 => Ok(Self::I2c0TxThreshold),
            79 => Ok(Self::I2c0AcqStretch),
            80 => Ok(Self::I2c0UnexpStop),
            81 => Ok(Self::I2c0HostTimeout),
            82 => Ok(Self::Uart0TxWatermark),
            83 => Ok(Self::Uart0RxWatermark),
            84 => Ok(Self::Uart0TxDone),
            85 => Ok(Self::Uart0RxOverflow),
            86 => Ok(Self::Uart0RxFrameErr),
            87 => Ok(Self::Uart0RxBreakErr),
            88 => Ok(Self::Uart0RxTimeout),
            89 => Ok(Self::Uart0RxParityErr),
            90 => Ok(Self::Uart0TxEmpty),
            91 => Ok(Self::RvTimerTimerExpiredHart0Timer0),
            92 => Ok(Self::AonTimerAonWkupTimerExpired),
            93 => Ok(Self::AonTimerAonWdogTimerBark),
            94 => Ok(Self::PwrmgrAonWakeup),
            95 => Ok(Self::FlashCtrlProgEmpty),
            96 => Ok(Self::FlashCtrlProgLvl),
            97 => Ok(Self::FlashCtrlRdFull),
            98 => Ok(Self::FlashCtrlRdLvl),
            99 => Ok(Self::FlashCtrlOpDone),
            100 => Ok(Self::FlashCtrlCorrErr),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Target.
///
/// Enumeration used to determine which set of IE, CC, threshold registers to
/// access for a given interrupt target.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicTarget {
    /// Ibex Core 0
    Ibex0 = 0,
}

/// PLIC Interrupt Source to Peripheral Map
///
/// This array is a mapping from `PlicIrqId` to
/// `PlicPeripheral`.
pub const PLIC_INTERRUPT_FOR_PERIPHERAL: [PlicPeripheral; 101] = [
    // None -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // HmacHmacDone -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // HmacFifoEmpty -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // HmacHmacErr -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // KmacKmacDone -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // KmacFifoEmpty -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // KmacKmacErr -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // CsrngCsCmdReqDone -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsEntropyReq -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsHwInstExc -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsFatalErr -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // EntropySrcEsEntropyValid -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // EntropySrcEsHealthTestFailed -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // EntropySrcEsObserveFifoReady -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // EntropySrcEsFatalErr -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // Edn0EdnCmdReqDone -> PlicPeripheral::Edn0
    PlicPeripheral::Edn0,
    // Edn0EdnFatalErr -> PlicPeripheral::Edn0
    PlicPeripheral::Edn0,
    // OtbnDone -> PlicPeripheral::Otbn
    PlicPeripheral::Otbn,
    // KeymgrOpDone -> PlicPeripheral::Keymgr
    PlicPeripheral::Keymgr,
    // AlertHandlerClassa -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassb -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassc -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassd -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // OtpCtrlOtpOperationDone -> PlicPeripheral::OtpCtrl
    PlicPeripheral::OtpCtrl,
    // OtpCtrlOtpError -> PlicPeripheral::OtpCtrl
    PlicPeripheral::OtpCtrl,
    // SensorCtrlIoStatusChange -> PlicPeripheral::SensorCtrl
    PlicPeripheral::SensorCtrl,
    // SensorCtrlInitStatusChange -> PlicPeripheral::SensorCtrl
    PlicPeripheral::SensorCtrl,
    // SpiDeviceUploadCmdfifoNotEmpty -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceUploadPayloadNotEmpty -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceUploadPayloadOverflow -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceReadbufWatermark -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceReadbufFlip -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceTpmHeaderNotEmpty -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceTpmRdfifoCmdEnd -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceTpmRdfifoDrop -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // GpioGpio0 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio1 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio2 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio3 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio4 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio5 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio6 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio7 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio8 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio9 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio10 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio11 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio12 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio13 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio14 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio15 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio16 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio17 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio18 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio19 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio20 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio21 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio22 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio23 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio24 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio25 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio26 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio27 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio28 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio29 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio30 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio31 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // I2c0FmtThreshold -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0RxThreshold -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0AcqThreshold -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0RxOverflow -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0ControllerHalt -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0SclInterference -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0SdaInterference -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0StretchTimeout -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0SdaUnstable -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0CmdComplete -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0TxStretch -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0TxThreshold -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0AcqStretch -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0UnexpStop -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0HostTimeout -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // Uart0TxWatermark -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxWatermark -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0TxDone -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxOverflow -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxFrameErr -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxBreakErr -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxTimeout -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxParityErr -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0TxEmpty -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // RvTimerTimerExpiredHart0Timer0 -> PlicPeripheral::RvTimer
    PlicPeripheral::RvTimer,
    // AonTimerAonWkupTimerExpired -> PlicPeripheral::AonTimerAon
    PlicPeripheral::AonTimerAon,
    // AonTimerAonWdogTimerBark -> PlicPeripheral::AonTimerAon
    PlicPeripheral::AonTimerAon,
    // PwrmgrAonWakeup -> PlicPeripheral::PwrmgrAon
    PlicPeripheral::PwrmgrAon,
    // FlashCtrlProgEmpty -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
    // FlashCtrlProgLvl -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
    // FlashCtrlRdFull -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
    // FlashCtrlRdLvl -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
    // FlashCtrlOpDone -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
    // FlashCtrlCorrErr -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
];

/// Alert Handler Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// alert.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum AlertPeripheral {
    /// External Peripheral
    External = 0,
    /// aes
    Aes = 1,
    /// hmac
    Hmac = 2,
    /// kmac
    Kmac = 3,
    /// csrng
    Csrng = 4,
    /// entropy_src
    EntropySrc = 5,
    /// edn0
    Edn0 = 6,
    /// otbn
    Otbn = 7,
    /// keymgr
    Keymgr = 8,
    /// lc_ctrl
    LcCtrl = 9,
    /// otp_ctrl
    OtpCtrl = 10,
    /// sensor_ctrl
    SensorCtrl = 11,
    /// spi_device
    SpiDevice = 12,
    /// gpio
    Gpio = 13,
    /// i2c0
    I2c0 = 14,
    /// uart0
    Uart0 = 15,
    /// rv_plic
    RvPlic = 16,
    /// rv_timer
    RvTimer = 17,
    /// aon_timer_aon
    AonTimerAon = 18,
    /// pwrmgr_aon
    PwrmgrAon = 19,
    /// clkmgr_aon
    ClkmgrAon = 20,
    /// rstmgr_aon
    RstmgrAon = 21,
    /// pinmux_aon
    PinmuxAon = 22,
    /// rom_ctrl
    RomCtrl = 23,
    /// sram_ctrl
    SramCtrl = 24,
    /// flash_ctrl
    FlashCtrl = 25,
    /// rv_core_ibex
    RvCoreIbex = 26,
}

/// Alert Handler Alert Source.
///
/// Enumeration of all Alert Handler Alert Sources. The alert sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum AlertId {
    /// aes_recov_ctrl_update_err
    AesRecovCtrlUpdateErr = 0,
    /// aes_fatal_fault
    AesFatalFault = 1,
    /// hmac_fatal_fault
    HmacFatalFault = 2,
    /// kmac_recov_operation_err
    KmacRecovOperationErr = 3,
    /// kmac_fatal_fault_err
    KmacFatalFaultErr = 4,
    /// csrng_recov_alert
    CsrngRecovAlert = 5,
    /// csrng_fatal_alert
    CsrngFatalAlert = 6,
    /// entropy_src_recov_alert
    EntropySrcRecovAlert = 7,
    /// entropy_src_fatal_alert
    EntropySrcFatalAlert = 8,
    /// edn0_recov_alert
    Edn0RecovAlert = 9,
    /// edn0_fatal_alert
    Edn0FatalAlert = 10,
    /// otbn_fatal
    OtbnFatal = 11,
    /// otbn_recov
    OtbnRecov = 12,
    /// keymgr_recov_operation_err
    KeymgrRecovOperationErr = 13,
    /// keymgr_fatal_fault_err
    KeymgrFatalFaultErr = 14,
    /// lc_ctrl_fatal_prog_error
    LcCtrlFatalProgError = 15,
    /// lc_ctrl_fatal_state_error
    LcCtrlFatalStateError = 16,
    /// lc_ctrl_fatal_bus_integ_error
    LcCtrlFatalBusIntegError = 17,
    /// otp_ctrl_fatal_macro_error
    OtpCtrlFatalMacroError = 18,
    /// otp_ctrl_fatal_check_error
    OtpCtrlFatalCheckError = 19,
    /// otp_ctrl_fatal_bus_integ_error
    OtpCtrlFatalBusIntegError = 20,
    /// otp_ctrl_fatal_prim_otp_alert
    OtpCtrlFatalPrimOtpAlert = 21,
    /// otp_ctrl_recov_prim_otp_alert
    OtpCtrlRecovPrimOtpAlert = 22,
    /// sensor_ctrl_recov_alert
    SensorCtrlRecovAlert = 23,
    /// sensor_ctrl_fatal_alert
    SensorCtrlFatalAlert = 24,
    /// spi_device_fatal_fault
    SpiDeviceFatalFault = 25,
    /// gpio_fatal_fault
    GpioFatalFault = 26,
    /// i2c0_fatal_fault
    I2c0FatalFault = 27,
    /// uart0_fatal_fault
    Uart0FatalFault = 28,
    /// rv_plic_fatal_fault
    RvPlicFatalFault = 29,
    /// rv_timer_fatal_fault
    RvTimerFatalFault = 30,
    /// aon_timer_aon_fatal_fault
    AonTimerAonFatalFault = 31,
    /// pwrmgr_aon_fatal_fault
    PwrmgrAonFatalFault = 32,
    /// clkmgr_aon_recov_fault
    ClkmgrAonRecovFault = 33,
    /// clkmgr_aon_fatal_fault
    ClkmgrAonFatalFault = 34,
    /// rstmgr_aon_fatal_fault
    RstmgrAonFatalFault = 35,
    /// rstmgr_aon_fatal_cnsty_fault
    RstmgrAonFatalCnstyFault = 36,
    /// pinmux_aon_fatal_fault
    PinmuxAonFatalFault = 37,
    /// rom_ctrl_fatal
    RomCtrlFatal = 38,
    /// sram_ctrl_fatal_error
    SramCtrlFatalError = 39,
    /// flash_ctrl_recov_err
    FlashCtrlRecovErr = 40,
    /// flash_ctrl_fatal_std_err
    FlashCtrlFatalStdErr = 41,
    /// flash_ctrl_fatal_err
    FlashCtrlFatalErr = 42,
    /// flash_ctrl_fatal_prim_flash_alert
    FlashCtrlFatalPrimFlashAlert = 43,
    /// flash_ctrl_recov_prim_flash_alert
    FlashCtrlRecovPrimFlashAlert = 44,
    /// rv_core_ibex_fatal_sw_err
    RvCoreIbexFatalSwErr = 45,
    /// rv_core_ibex_recov_sw_err
    RvCoreIbexRecovSwErr = 46,
    /// rv_core_ibex_fatal_hw_err
    RvCoreIbexFatalHwErr = 47,
    /// rv_core_ibex_recov_hw_err
    RvCoreIbexRecovHwErr = 48,
}

impl TryFrom<u32> for AlertId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::AesRecovCtrlUpdateErr),
            1 => Ok(Self::AesFatalFault),
            2 => Ok(Self::HmacFatalFault),
            3 => Ok(Self::KmacRecovOperationErr),
            4 => Ok(Self::KmacFatalFaultErr),
            5 => Ok(Self::CsrngRecovAlert),
            6 => Ok(Self::CsrngFatalAlert),
            7 => Ok(Self::EntropySrcRecovAlert),
            8 => Ok(Self::EntropySrcFatalAlert),
            9 => Ok(Self::Edn0RecovAlert),
            10 => Ok(Self::Edn0FatalAlert),
            11 => Ok(Self::OtbnFatal),
            12 => Ok(Self::OtbnRecov),
            13 => Ok(Self::KeymgrRecovOperationErr),
            14 => Ok(Self::KeymgrFatalFaultErr),
            15 => Ok(Self::LcCtrlFatalProgError),
            16 => Ok(Self::LcCtrlFatalStateError),
            17 => Ok(Self::LcCtrlFatalBusIntegError),
            18 => Ok(Self::OtpCtrlFatalMacroError),
            19 => Ok(Self::OtpCtrlFatalCheckError),
            20 => Ok(Self::OtpCtrlFatalBusIntegError),
            21 => Ok(Self::OtpCtrlFatalPrimOtpAlert),
            22 => Ok(Self::OtpCtrlRecovPrimOtpAlert),
            23 => Ok(Self::SensorCtrlRecovAlert),
            24 => Ok(Self::SensorCtrlFatalAlert),
            25 => Ok(Self::SpiDeviceFatalFault),
            26 => Ok(Self::GpioFatalFault),
            27 => Ok(Self::I2c0FatalFault),
            28 => Ok(Self::Uart0FatalFault),
            29 => Ok(Self::RvPlicFatalFault),
            30 => Ok(Self::RvTimerFatalFault),
            31 => Ok(Self::AonTimerAonFatalFault),
            32 => Ok(Self::PwrmgrAonFatalFault),
            33 => Ok(Self::ClkmgrAonRecovFault),
            34 => Ok(Self::ClkmgrAonFatalFault),
            35 => Ok(Self::RstmgrAonFatalFault),
            36 => Ok(Self::RstmgrAonFatalCnstyFault),
            37 => Ok(Self::PinmuxAonFatalFault),
            38 => Ok(Self::RomCtrlFatal),
            39 => Ok(Self::SramCtrlFatalError),
            40 => Ok(Self::FlashCtrlRecovErr),
            41 => Ok(Self::FlashCtrlFatalStdErr),
            42 => Ok(Self::FlashCtrlFatalErr),
            43 => Ok(Self::FlashCtrlFatalPrimFlashAlert),
            44 => Ok(Self::FlashCtrlRecovPrimFlashAlert),
            45 => Ok(Self::RvCoreIbexFatalSwErr),
            46 => Ok(Self::RvCoreIbexRecovSwErr),
            47 => Ok(Self::RvCoreIbexFatalHwErr),
            48 => Ok(Self::RvCoreIbexRecovHwErr),
            _ => Err(val),
        }
    }
}

/// Alert Handler Alert Source to Peripheral Map
///
/// This array is a mapping from `AlertId` to
/// `AlertPeripheral`.
pub const ALERT_FOR_PERIPHERAL: [AlertPeripheral; 49] = [
    // AesRecovCtrlUpdateErr -> AlertPeripheral::Aes
    AlertPeripheral::Aes,
    // AesFatalFault -> AlertPeripheral::Aes
    AlertPeripheral::Aes,
    // HmacFatalFault -> AlertPeripheral::Hmac
    AlertPeripheral::Hmac,
    // KmacRecovOperationErr -> AlertPeripheral::Kmac
    AlertPeripheral::Kmac,
    // KmacFatalFaultErr -> AlertPeripheral::Kmac
    AlertPeripheral::Kmac,
    // CsrngRecovAlert -> AlertPeripheral::Csrng
    AlertPeripheral::Csrng,
    // CsrngFatalAlert -> AlertPeripheral::Csrng
    AlertPeripheral::Csrng,
    // EntropySrcRecovAlert -> AlertPeripheral::EntropySrc
    AlertPeripheral::EntropySrc,
    // EntropySrcFatalAlert -> AlertPeripheral::EntropySrc
    AlertPeripheral::EntropySrc,
    // Edn0RecovAlert -> AlertPeripheral::Edn0
    AlertPeripheral::Edn0,
    // Edn0FatalAlert -> AlertPeripheral::Edn0
    AlertPeripheral::Edn0,
    // OtbnFatal -> AlertPeripheral::Otbn
    AlertPeripheral::Otbn,
    // OtbnRecov -> AlertPeripheral::Otbn
    AlertPeripheral::Otbn,
    // KeymgrRecovOperationErr -> AlertPeripheral::Keymgr
    AlertPeripheral::Keymgr,
    // KeymgrFatalFaultErr -> AlertPeripheral::Keymgr
    AlertPeripheral::Keymgr,
    // LcCtrlFatalProgError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // LcCtrlFatalStateError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // LcCtrlFatalBusIntegError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // OtpCtrlFatalMacroError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalCheckError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalBusIntegError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalPrimOtpAlert -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlRecovPrimOtpAlert -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // SensorCtrlRecovAlert -> AlertPeripheral::SensorCtrl
    AlertPeripheral::SensorCtrl,
    // SensorCtrlFatalAlert -> AlertPeripheral::SensorCtrl
    AlertPeripheral::SensorCtrl,
    // SpiDeviceFatalFault -> AlertPeripheral::SpiDevice
    AlertPeripheral::SpiDevice,
    // GpioFatalFault -> AlertPeripheral::Gpio
    AlertPeripheral::Gpio,
    // I2c0FatalFault -> AlertPeripheral::I2c0
    AlertPeripheral::I2c0,
    // Uart0FatalFault -> AlertPeripheral::Uart0
    AlertPeripheral::Uart0,
    // RvPlicFatalFault -> AlertPeripheral::RvPlic
    AlertPeripheral::RvPlic,
    // RvTimerFatalFault -> AlertPeripheral::RvTimer
    AlertPeripheral::RvTimer,
    // AonTimerAonFatalFault -> AlertPeripheral::AonTimerAon
    AlertPeripheral::AonTimerAon,
    // PwrmgrAonFatalFault -> AlertPeripheral::PwrmgrAon
    AlertPeripheral::PwrmgrAon,
    // ClkmgrAonRecovFault -> AlertPeripheral::ClkmgrAon
    AlertPeripheral::ClkmgrAon,
    // ClkmgrAonFatalFault -> AlertPeripheral::ClkmgrAon
    AlertPeripheral::ClkmgrAon,
    // RstmgrAonFatalFault -> AlertPeripheral::RstmgrAon
    AlertPeripheral::RstmgrAon,
    // RstmgrAonFatalCnstyFault -> AlertPeripheral::RstmgrAon
    AlertPeripheral::RstmgrAon,
    // PinmuxAonFatalFault -> AlertPeripheral::PinmuxAon
    AlertPeripheral::PinmuxAon,
    // RomCtrlFatal -> AlertPeripheral::RomCtrl
    AlertPeripheral::RomCtrl,
    // SramCtrlFatalError -> AlertPeripheral::SramCtrl
    AlertPeripheral::SramCtrl,
    // FlashCtrlRecovErr -> AlertPeripheral::FlashCtrl
    AlertPeripheral::FlashCtrl,
    // FlashCtrlFatalStdErr -> AlertPeripheral::FlashCtrl
    AlertPeripheral::FlashCtrl,
    // FlashCtrlFatalErr -> AlertPeripheral::FlashCtrl
    AlertPeripheral::FlashCtrl,
    // FlashCtrlFatalPrimFlashAlert -> AlertPeripheral::FlashCtrl
    AlertPeripheral::FlashCtrl,
    // FlashCtrlRecovPrimFlashAlert -> AlertPeripheral::FlashCtrl
    AlertPeripheral::FlashCtrl,
    // RvCoreIbexFatalSwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexRecovSwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexFatalHwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexRecovHwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
];

// PERIPH_INSEL ranges from 0 to NUM_MIO_PADS + 2 -1}
//  0 and 1 are tied to value 0 and 1
pub const NUM_MIO_PADS: usize = 16;
pub const NUM_DIO_PADS: usize = 6;

pub const PINMUX_MIO_PERIPH_INSEL_IDX_OFFSET: usize = 2;
pub const PINMUX_PERIPH_OUTSEL_IDX_OFFSET: usize = 3;

/// Pinmux Peripheral Input.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxPeripheralIn {
    /// Peripheral Input 0
    GpioGpio0 = 0,
    /// Peripheral Input 1
    GpioGpio1 = 1,
    /// Peripheral Input 2
    GpioGpio2 = 2,
    /// Peripheral Input 3
    GpioGpio3 = 3,
    /// Peripheral Input 4
    GpioGpio4 = 4,
    /// Peripheral Input 5
    GpioGpio5 = 5,
    /// Peripheral Input 6
    GpioGpio6 = 6,
    /// Peripheral Input 7
    GpioGpio7 = 7,
    /// Peripheral Input 8
    GpioGpio8 = 8,
    /// Peripheral Input 9
    GpioGpio9 = 9,
    /// Peripheral Input 10
    GpioGpio10 = 10,
    /// Peripheral Input 11
    GpioGpio11 = 11,
    /// Peripheral Input 12
    GpioGpio12 = 12,
    /// Peripheral Input 13
    GpioGpio13 = 13,
    /// Peripheral Input 14
    GpioGpio14 = 14,
    /// Peripheral Input 15
    GpioGpio15 = 15,
    /// Peripheral Input 16
    GpioGpio16 = 16,
    /// Peripheral Input 17
    GpioGpio17 = 17,
    /// Peripheral Input 18
    GpioGpio18 = 18,
    /// Peripheral Input 19
    GpioGpio19 = 19,
    /// Peripheral Input 20
    GpioGpio20 = 20,
    /// Peripheral Input 21
    GpioGpio21 = 21,
    /// Peripheral Input 22
    GpioGpio22 = 22,
    /// Peripheral Input 23
    GpioGpio23 = 23,
    /// Peripheral Input 24
    GpioGpio24 = 24,
    /// Peripheral Input 25
    GpioGpio25 = 25,
    /// Peripheral Input 26
    GpioGpio26 = 26,
    /// Peripheral Input 27
    GpioGpio27 = 27,
    /// Peripheral Input 28
    GpioGpio28 = 28,
    /// Peripheral Input 29
    GpioGpio29 = 29,
    /// Peripheral Input 30
    GpioGpio30 = 30,
    /// Peripheral Input 31
    GpioGpio31 = 31,
    /// Peripheral Input 32
    I2c0Sda = 32,
    /// Peripheral Input 33
    I2c0Scl = 33,
    /// Peripheral Input 34
    Uart0Rx = 34,
    /// Peripheral Input 35
    SpiDeviceTpmCsb = 35,
    /// Peripheral Input 36
    FlashCtrlTck = 36,
    /// Peripheral Input 37
    FlashCtrlTms = 37,
    /// Peripheral Input 38
    FlashCtrlTdi = 38,
}

impl TryFrom<u32> for PinmuxPeripheralIn {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::GpioGpio0),
            1 => Ok(Self::GpioGpio1),
            2 => Ok(Self::GpioGpio2),
            3 => Ok(Self::GpioGpio3),
            4 => Ok(Self::GpioGpio4),
            5 => Ok(Self::GpioGpio5),
            6 => Ok(Self::GpioGpio6),
            7 => Ok(Self::GpioGpio7),
            8 => Ok(Self::GpioGpio8),
            9 => Ok(Self::GpioGpio9),
            10 => Ok(Self::GpioGpio10),
            11 => Ok(Self::GpioGpio11),
            12 => Ok(Self::GpioGpio12),
            13 => Ok(Self::GpioGpio13),
            14 => Ok(Self::GpioGpio14),
            15 => Ok(Self::GpioGpio15),
            16 => Ok(Self::GpioGpio16),
            17 => Ok(Self::GpioGpio17),
            18 => Ok(Self::GpioGpio18),
            19 => Ok(Self::GpioGpio19),
            20 => Ok(Self::GpioGpio20),
            21 => Ok(Self::GpioGpio21),
            22 => Ok(Self::GpioGpio22),
            23 => Ok(Self::GpioGpio23),
            24 => Ok(Self::GpioGpio24),
            25 => Ok(Self::GpioGpio25),
            26 => Ok(Self::GpioGpio26),
            27 => Ok(Self::GpioGpio27),
            28 => Ok(Self::GpioGpio28),
            29 => Ok(Self::GpioGpio29),
            30 => Ok(Self::GpioGpio30),
            31 => Ok(Self::GpioGpio31),
            32 => Ok(Self::I2c0Sda),
            33 => Ok(Self::I2c0Scl),
            34 => Ok(Self::Uart0Rx),
            35 => Ok(Self::SpiDeviceTpmCsb),
            36 => Ok(Self::FlashCtrlTck),
            37 => Ok(Self::FlashCtrlTms),
            38 => Ok(Self::FlashCtrlTdi),
            _ => Err(val),
        }
    }
}

/// Pinmux MIO Input Selector.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxInsel {
    /// Tie constantly to zero
    ConstantZero = 0,
    /// Tie constantly to one
    ConstantOne = 1,
    /// MIO Pad 0
    Mio0 = 2,
    /// MIO Pad 1
    Mio1 = 3,
    /// MIO Pad 2
    Mio2 = 4,
    /// MIO Pad 3
    Mio3 = 5,
    /// MIO Pad 4
    Mio4 = 6,
    /// MIO Pad 5
    Mio5 = 7,
    /// MIO Pad 6
    Mio6 = 8,
    /// MIO Pad 7
    Mio7 = 9,
    /// MIO Pad 8
    Mio8 = 10,
    /// MIO Pad 9
    Mio9 = 11,
    /// MIO Pad 10
    Mio10 = 12,
    /// MIO Pad 11
    Mio11 = 13,
    /// MIO Pad 12
    Mio12 = 14,
    /// MIO Pad 13
    Mio13 = 15,
    /// MIO Pad 14
    Mio14 = 16,
    /// MIO Pad 15
    Mio15 = 17,
}

impl TryFrom<u32> for PinmuxInsel {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::ConstantZero),
            1 => Ok(Self::ConstantOne),
            2 => Ok(Self::Mio0),
            3 => Ok(Self::Mio1),
            4 => Ok(Self::Mio2),
            5 => Ok(Self::Mio3),
            6 => Ok(Self::Mio4),
            7 => Ok(Self::Mio5),
            8 => Ok(Self::Mio6),
            9 => Ok(Self::Mio7),
            10 => Ok(Self::Mio8),
            11 => Ok(Self::Mio9),
            12 => Ok(Self::Mio10),
            13 => Ok(Self::Mio11),
            14 => Ok(Self::Mio12),
            15 => Ok(Self::Mio13),
            16 => Ok(Self::Mio14),
            17 => Ok(Self::Mio15),
            _ => Err(val),
        }
    }
}

/// Pinmux MIO Output.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxMioOut {
    /// MIO Pad 0
    Mio0 = 0,
    /// MIO Pad 1
    Mio1 = 1,
    /// MIO Pad 2
    Mio2 = 2,
    /// MIO Pad 3
    Mio3 = 3,
    /// MIO Pad 4
    Mio4 = 4,
    /// MIO Pad 5
    Mio5 = 5,
    /// MIO Pad 6
    Mio6 = 6,
    /// MIO Pad 7
    Mio7 = 7,
    /// MIO Pad 8
    Mio8 = 8,
    /// MIO Pad 9
    Mio9 = 9,
    /// MIO Pad 10
    Mio10 = 10,
    /// MIO Pad 11
    Mio11 = 11,
    /// MIO Pad 12
    Mio12 = 12,
    /// MIO Pad 13
    Mio13 = 13,
    /// MIO Pad 14
    Mio14 = 14,
    /// MIO Pad 15
    Mio15 = 15,
}

impl TryFrom<u32> for PinmuxMioOut {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Mio0),
            1 => Ok(Self::Mio1),
            2 => Ok(Self::Mio2),
            3 => Ok(Self::Mio3),
            4 => Ok(Self::Mio4),
            5 => Ok(Self::Mio5),
            6 => Ok(Self::Mio6),
            7 => Ok(Self::Mio7),
            8 => Ok(Self::Mio8),
            9 => Ok(Self::Mio9),
            10 => Ok(Self::Mio10),
            11 => Ok(Self::Mio11),
            12 => Ok(Self::Mio12),
            13 => Ok(Self::Mio13),
            14 => Ok(Self::Mio14),
            15 => Ok(Self::Mio15),
            _ => Err(val),
        }
    }
}

/// Pinmux Peripheral Output Selector.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxOutsel {
    /// Tie constantly to zero
    ConstantZero = 0,
    /// Tie constantly to one
    ConstantOne = 1,
    /// Tie constantly to high-Z
    ConstantHighZ = 2,
    /// Peripheral Output 0
    GpioGpio0 = 3,
    /// Peripheral Output 1
    GpioGpio1 = 4,
    /// Peripheral Output 2
    GpioGpio2 = 5,
    /// Peripheral Output 3
    GpioGpio3 = 6,
    /// Peripheral Output 4
    GpioGpio4 = 7,
    /// Peripheral Output 5
    GpioGpio5 = 8,
    /// Peripheral Output 6
    GpioGpio6 = 9,
    /// Peripheral Output 7
    GpioGpio7 = 10,
    /// Peripheral Output 8
    GpioGpio8 = 11,
    /// Peripheral Output 9
    GpioGpio9 = 12,
    /// Peripheral Output 10
    GpioGpio10 = 13,
    /// Peripheral Output 11
    GpioGpio11 = 14,
    /// Peripheral Output 12
    GpioGpio12 = 15,
    /// Peripheral Output 13
    GpioGpio13 = 16,
    /// Peripheral Output 14
    GpioGpio14 = 17,
    /// Peripheral Output 15
    GpioGpio15 = 18,
    /// Peripheral Output 16
    GpioGpio16 = 19,
    /// Peripheral Output 17
    GpioGpio17 = 20,
    /// Peripheral Output 18
    GpioGpio18 = 21,
    /// Peripheral Output 19
    GpioGpio19 = 22,
    /// Peripheral Output 20
    GpioGpio20 = 23,
    /// Peripheral Output 21
    GpioGpio21 = 24,
    /// Peripheral Output 22
    GpioGpio22 = 25,
    /// Peripheral Output 23
    GpioGpio23 = 26,
    /// Peripheral Output 24
    GpioGpio24 = 27,
    /// Peripheral Output 25
    GpioGpio25 = 28,
    /// Peripheral Output 26
    GpioGpio26 = 29,
    /// Peripheral Output 27
    GpioGpio27 = 30,
    /// Peripheral Output 28
    GpioGpio28 = 31,
    /// Peripheral Output 29
    GpioGpio29 = 32,
    /// Peripheral Output 30
    GpioGpio30 = 33,
    /// Peripheral Output 31
    GpioGpio31 = 34,
    /// Peripheral Output 32
    I2c0Sda = 35,
    /// Peripheral Output 33
    I2c0Scl = 36,
    /// Peripheral Output 34
    Uart0Tx = 37,
    /// Peripheral Output 35
    FlashCtrlTdo = 38,
    /// Peripheral Output 36
    SensorCtrlAstDebugOut0 = 39,
    /// Peripheral Output 37
    SensorCtrlAstDebugOut1 = 40,
    /// Peripheral Output 38
    SensorCtrlAstDebugOut2 = 41,
    /// Peripheral Output 39
    SensorCtrlAstDebugOut3 = 42,
    /// Peripheral Output 40
    SensorCtrlAstDebugOut4 = 43,
    /// Peripheral Output 41
    SensorCtrlAstDebugOut5 = 44,
    /// Peripheral Output 42
    SensorCtrlAstDebugOut6 = 45,
    /// Peripheral Output 43
    SensorCtrlAstDebugOut7 = 46,
    /// Peripheral Output 44
    SensorCtrlAstDebugOut8 = 47,
    /// Peripheral Output 45
    OtpMacroTest0 = 48,
}

impl TryFrom<u32> for PinmuxOutsel {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::ConstantZero),
            1 => Ok(Self::ConstantOne),
            2 => Ok(Self::ConstantHighZ),
            3 => Ok(Self::GpioGpio0),
            4 => Ok(Self::GpioGpio1),
            5 => Ok(Self::GpioGpio2),
            6 => Ok(Self::GpioGpio3),
            7 => Ok(Self::GpioGpio4),
            8 => Ok(Self::GpioGpio5),
            9 => Ok(Self::GpioGpio6),
            10 => Ok(Self::GpioGpio7),
            11 => Ok(Self::GpioGpio8),
            12 => Ok(Self::GpioGpio9),
            13 => Ok(Self::GpioGpio10),
            14 => Ok(Self::GpioGpio11),
            15 => Ok(Self::GpioGpio12),
            16 => Ok(Self::GpioGpio13),
            17 => Ok(Self::GpioGpio14),
            18 => Ok(Self::GpioGpio15),
            19 => Ok(Self::GpioGpio16),
            20 => Ok(Self::GpioGpio17),
            21 => Ok(Self::GpioGpio18),
            22 => Ok(Self::GpioGpio19),
            23 => Ok(Self::GpioGpio20),
            24 => Ok(Self::GpioGpio21),
            25 => Ok(Self::GpioGpio22),
            26 => Ok(Self::GpioGpio23),
            27 => Ok(Self::GpioGpio24),
            28 => Ok(Self::GpioGpio25),
            29 => Ok(Self::GpioGpio26),
            30 => Ok(Self::GpioGpio27),
            31 => Ok(Self::GpioGpio28),
            32 => Ok(Self::GpioGpio29),
            33 => Ok(Self::GpioGpio30),
            34 => Ok(Self::GpioGpio31),
            35 => Ok(Self::I2c0Sda),
            36 => Ok(Self::I2c0Scl),
            37 => Ok(Self::Uart0Tx),
            38 => Ok(Self::FlashCtrlTdo),
            39 => Ok(Self::SensorCtrlAstDebugOut0),
            40 => Ok(Self::SensorCtrlAstDebugOut1),
            41 => Ok(Self::SensorCtrlAstDebugOut2),
            42 => Ok(Self::SensorCtrlAstDebugOut3),
            43 => Ok(Self::SensorCtrlAstDebugOut4),
            44 => Ok(Self::SensorCtrlAstDebugOut5),
            45 => Ok(Self::SensorCtrlAstDebugOut6),
            46 => Ok(Self::SensorCtrlAstDebugOut7),
            47 => Ok(Self::SensorCtrlAstDebugOut8),
            48 => Ok(Self::OtpMacroTest0),
            _ => Err(val),
        }
    }
}

/// Dedicated Pad Selects
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum DirectPads {
    SpiDeviceSd0 = 0,
    SpiDeviceSd1 = 1,
    SpiDeviceSd2 = 2,
    SpiDeviceSd3 = 3,
    SpiDeviceSck = 4,
    SpiDeviceCsb = 5,
}

impl TryFrom<u32> for DirectPads {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::SpiDeviceSd0),
            1 => Ok(Self::SpiDeviceSd1),
            2 => Ok(Self::SpiDeviceSd2),
            3 => Ok(Self::SpiDeviceSd3),
            4 => Ok(Self::SpiDeviceSck),
            5 => Ok(Self::SpiDeviceCsb),
            _ => Err(val),
        }
    }
}

/// Muxed Pad Selects
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum MuxedPads {
    Mio0 = 0,
    Mio1 = 1,
    Mio2 = 2,
    Mio3 = 3,
    Mio4 = 4,
    Mio5 = 5,
    Mio6 = 6,
    Mio7 = 7,
    Mio8 = 8,
    Mio9 = 9,
    Mio10 = 10,
    Mio11 = 11,
    Mio12 = 12,
    Mio13 = 13,
    Mio14 = 14,
    Mio15 = 15,
}

impl TryFrom<u32> for MuxedPads {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Mio0),
            1 => Ok(Self::Mio1),
            2 => Ok(Self::Mio2),
            3 => Ok(Self::Mio3),
            4 => Ok(Self::Mio4),
            5 => Ok(Self::Mio5),
            6 => Ok(Self::Mio6),
            7 => Ok(Self::Mio7),
            8 => Ok(Self::Mio8),
            9 => Ok(Self::Mio9),
            10 => Ok(Self::Mio10),
            11 => Ok(Self::Mio11),
            12 => Ok(Self::Mio12),
            13 => Ok(Self::Mio13),
            14 => Ok(Self::Mio14),
            15 => Ok(Self::Mio15),
            _ => Err(val),
        }
    }
}

/// Power Manager Wakeup Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerWakeUps {
    SensorCtrlWkupReq = 0,
    AonTimerAonWkupReq = 1,
    PinmuxAonPinWkupReq = 2,
}

/// Reset Manager Software Controlled Resets
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum ResetManagerSwResets {
    SpiDevice = 0,
    I2c0 = 1,
}

/// Power Manager Reset Request Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerResetRequests {
    AonTimerAonAonTimerRstReq = 0,
}

/// Clock Manager Software-Controlled ("Gated") Clocks.
///
/// The Software has full control over these clocks.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum GateableClocks {
    /// Clock clk_io_div4_peri in group peri
    IoDiv4Peri = 0,
    /// Clock clk_io_div2_peri in group peri
    IoDiv2Peri = 1,
}

/// Clock Manager Software-Hinted Clocks.
///
/// The Software has partial control over these clocks. It can ask them to stop,
/// but the clock manager is in control of whether the clock actually is stopped.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum HintableClocks {
    /// Clock clk_main_aes in group trans
    MainAes = 0,
    /// Clock clk_main_hmac in group trans
    MainHmac = 1,
    /// Clock clk_main_kmac in group trans
    MainKmac = 2,
    /// Clock clk_main_otbn in group trans
    MainOtbn = 3,
}

/// MMIO Region
///
/// MMIO region for SafeRoot. Excludes ROM, SRAM, and flash data memory.
pub const TOP_SAFEROOT_MMIO_BASE_ADDR: usize = 0x40000000;
pub const TOP_SAFEROOT_MMIO_SIZE_BYTES: usize = 0x10000000;
